### ISSUE TITLE
RACETRACK shape issue

### ISSUE THREAD

**Issue by rdemaria** [MethodicalAcceleratorDesign/MAD-X#1000]
I understand that the old 3-parameter version is not supported anymore, such as

APERTYPE=RACETRACK, APERTURE={0.00000,0.01375,0.03375}

The equivalent 4-parameter version should be:

APERTYPE=RACETRACK, APERTURE={0.03375,0.01375+0.03375,0,0.03375}

Correct?

However it looks like the 0 in ap3 invalidates the shape with this error message

+=+=+= fatal: Illegal negative or too small value in aper_rectellipse for ap1 or ap2 (rectangle)

Fixing with a small non zero value seems to help

APERTYPE=RACETRACK, APERTURE={0.03375,0.01375+0.03375,0.001,0.03375}

but hints at a non correct handling of the shape.

**Comment by tpersson** [comment]
I completely missed this issue. I will have a look...

**Comment by tpersson** [comment]
Fixed in PR #1007
