### ISSUE TITLE
LaTeX User guide: link broken

### ISSUE THREAD

**Issue by roman-martin** [MethodicalAcceleratorDesign/MAD-X#1003]
The link in the latex user guide explaining the the use of aper_vx/aper_vy is broken in the pdf. It appears this is because the \href command https://github.com/MethodicalAcceleratorDesign/MAD-X/blob/71a1a5dc9fd2525971d1ac6aed5b4e12eae6e7a5/doc/latexuguide/aperture.tex#L159

requires a second parameter for the text of the link: 

`\href{<link>}{<link text>}`

In addition, I think the linked script is not ideal to explain aper_vx/aper_vy as it only uses the k-parameter and nothing else.

**Comment by tpersson** [comment]
Thanks a lot for the report and sorry for the slow reply. It has been fixed and will be included in the next release.
