### ISSUE TITLE
Cycling Weirdness

### ISSUE THREAD

**Issue by leonvanriesen** [MethodicalAcceleratorDesign/MAD-X#1015]
I have already discussed this with Tobias and we did some initial tests but thought this should be formalised with a ticket.

I found strange behaviour when introducing vertical bends with angle = 0 in the FCC-ee lattice. Basically the vertical dispersion around the ring depends on where the machine has been cycled. Example job file can be found at:

/afs/cern.ch/work/l/lvanries/public/cycling_bug

If it is cycled to the RF, far away from the vertical bends, the dispersion bump closes nicely. But if the sequence is cycled to the centre of the dispersion bump, the dispersion bump does not close and we get large dispersion everywhere. Similar problem with the y closed orbit. There are example plots in the repository above.

The problem might not be limited to FCC-ee and I would be happy to help with any further debugging.

**Comment by tpersson** [comment]
Thanks for submitting this as an issue as well! We will have a look...

**Comment by tpersson** [comment]
We were able to solve this by putting a tighter tolerance on the closed orbit search. Maybe this is something that should be done also in other cases when this is a problem.

**Comment by tpersson** [comment]
I will close this issue and open a new one..
