### ISSUE TITLE
beam beam definition

### ISSUE THREAD

**Issue by rdemaria** [MethodicalAcceleratorDesign/MAD-X#1021]
The charge of the bunch of the BEAMBEAM element depends on the CHARGE attribute multiplied by NPART of the beam. This assumes that the strong beam has the same number of particles of the weak. I propose to add a mechanism to allow defining the charge of the bunch of the beam-beam element decoupled from the charge of the current beam.

Adding a new attribute NPART in the BEAMBEAM element and, if present, use it instead of NPART defined in BEAM.

Requested by @giadarol, @skostogl, @sterbini.

**Comment by tpersson** [comment]
So the logic would be to check if there is a npart in the beam-beam element and in that case use it everywhere instead of the beam-npart. If not defined, default to the current behaviour?

**Comment by rdemaria** [comment]
Exactly! We did not want to break backward compatibility, but the present mechanism is really ill defined because the link between beam and beambeam applies only to special cases.

**Comment by tpersson** [comment]
I just started having a look at this and there is also a charge that is defined in the beam command. I guess in this case you also want to have the possibility to define it in the beam-beam element?

**Comment by rdemaria** [comment]
Precisely. We have situations for which the strong beam have different number of particles than the weak beam. We could probably also add charge for the case of p-Pb runs.

**Comment by tpersson** [comment]
Thanks for the fast reply. I just noticed that there is already a charge for the beam-beam element (default 1). I don't dare to say if the implemenntation is correct but it is used and it looks like someone has given it some thought.

**Comment by rdemaria** [comment]
Yes, I have forgotten! I am not sure if this charge is multiplied by the charge of the beam or it is just by the protob charge. I would need to check. Any way forget, we cannot change this it anyway. We can add npart instead without breaking past code.

**Comment by tpersson** [comment]
This is fixed in PR #1033
