### ISSUE TITLE
Store the output of the EMIT module in a TABLE

### ISSUE THREAD

**Issue by apoyet** [MethodicalAcceleratorDesign/MAD-X#1032]
Hi, 

Following several discussion, I open this issue concerning the EMIT module of MAD-X. 

It was in fact observed that the output of the EMIT module is only printed in the standard output and not stored anywhere. The BEAM emittance is updated in case DELTAP is set to zero, but not if DELTAP!=0. 

The request would be to write the output of the EMIT module in one or two tables, following the TWISS example (e.g, an EMITT_TABLE and EMITT_SUMM), with all the computed parameters. 

I remain at your disposal if needed, 

Cheers !

**Comment by tpersson** [comment]
This is fixed in PR #1049
