### ISSUE TITLE
[MAKETHIN] Using K0L (when defined) over ANGLE when MAKEDIPEDGE = TRUE

### ISSUE THREAD

**Issue by GuillaumeRD** [MethodicalAcceleratorDesign/MAD-X#1076]
When using MAKETHIN with MAKEDIPEDGE=TRUE, the dipole edges are created using the ANGLE parameter for each dipole even when a K0 (or K0L) has been defined for that same magnet, which is the way MAD-X would be told that said magnet is operating with a different radius.

**Comment by rdemaria** [comment]
being addressed in #1078

**Comment by rdemaria** [comment]
fixed in [#1173](https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/1173)
