### ISSUE TITLE
AC-dipole in PTC but not in convertor

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#108]
*Issue migrated from trac ticket # 108*

**component:** ptc_proper | **priority:** major
___
#### 2012-01-30 13:50:56: frank.schmidt commented

date: 2011.11.19
The AC-dipole is in PTC and lacking in the convertor.

___
#### 2012-01-30 13:51:16: @ldeniau changed title from *AC-dipole is in PTC but not in convertor* to *AC-dipole in PTC but not in convertor*

___
#### 2012-12-07 13:02:38: @ldeniau changed owner from ** to *piotr.skowronski*

___
#### 2012-12-07 13:02:38: @ldeniau changed status from *new* to *assigned*

**Comment by piotrskowronski** [comment]
Committed with pull request #537

Example MADX script
https://github.com/MethodicalAcceleratorDesign/MAD-X/blob/master/tests/test-ptc-track-acd-2/test-ptc-track-acd-2.madx
