### ISSUE TITLE
adding ktap on additional elements

### ISSUE THREAD

**Issue by rdemaria** [MethodicalAcceleratorDesign/MAD-X#1081]
From @ghislain-roy

>  indeed KTAP is currently implemented for bends, quadrupoles and sextupoles. I can extend the KTAP mechanism to octupoles and multipoles. 
> Implementing KTAP for the octupoles should be very straightforward. 
> Implementing KTAP for the general thin multipole means adding a single parameter for all components of the multipole. The only issue is to make sure it is taken into account everywhere the multipole components are used. 
> For other elements, remember that KTAP is intended to be used for "tapering circuits”. This parameter makes sense for most magnetic elements but does not make sense for solenoids, kickers, RF cavities, etc.

**Comment by ghislain-roy** [comment]
Code mostly completed.  I now need an example combining taper and makethin, and including octupoles and multipoles, to check that all is working fine. 
I have already inserted zero-strength octupoles and multipoles in an FCC lattice to check that taper is properly calculated. 
I would like to further test the usage of taper for octupoles and multipoles.

**Comment by ghislain-roy** [comment]
Sent an email to Helmut Burkhardt to request a test case.

**Comment by rdemaria** [comment]
f for factor I believe

**Comment by rdemaria** [comment]
addressed in f0774f6874973b82eb4d
