### ISSUE TITLE
One-turn map R symplectic deviation:  0.152312E-11 warning

### ISSUE THREAD

**Issue by zhuruihu** [MethodicalAcceleratorDesign/MAD-X#1089]
I am designing a ring with interaction region. I first finished the optics of the interaction region and then the other parts of the ring. But when I combine the optics of the interaction region and other parts together, One-turn map R symplectic deviation:  0.152312E-11 warning ocurrs. I wonder why this happens.
**ring:line=(matching1,7*fodo1,matching2,12*(fodo_arc1,fodo_arc2,fodo_arc3),matching3,matching4,20*fodo2,matching5,12*(fodo_arc4,fodo_arc5,fodo_arc6),matching6,matching7,8*fodo3,matching8,real_all);
use,sequence=ring;
twiss;**
real_all is the interaction region, others are other parts. The interaction region and other parts can run smoothly with Twiss command.

**Comment by rdemaria** [comment]
Which beam line elements are you using. If you can share the full file, I could have a look. Typically if you have large closed orbit, transfer matrices suffer from truncation errors as they are derived from 2nd order expanded maps from the origin.

**Comment by zhuruihu** [comment]
[ring.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/8260940/ring.txt)

**Comment by zhuruihu** [comment]
> Which beam line elements are you using. If you can share the full file, I could have a look. Typically if you have large closed orbit, transfer matrices suffer from truncation errors as they are derived from 2nd order expanded maps from the origin.

I've uploaded my file. Can you give it a look?

**Comment by zhuruihu** [comment]
When real_all(interaction region) is removed from the ring beamline, it's ok to use Twiss command. Meanwhile, when Twiss command is used on real_all, it's also ok. But when these two are connected, warning occurs.

**Comment by rdemaria** [comment]
I did not see anything particularly strange. I think the warning can be ignored as it looks like originating from the accumulation of numerical errors. I would close the issue here, but please feel free to reopen.
