### ISSUE TITLE
Create DOI for MAD-X

### ISSUE THREAD

**Issue by fsoubelet** [MethodicalAcceleratorDesign/MAD-X#1106]
Hi,

I'm always a bit at a loss on how to best or officially cite MAD-X. It would be very nice to had a DOI associated with each release of the software.

It is very easy to do so with [Zenodo](https://zenodo.org) for Github repositories, here is a succint tutorial by the Github guys themselves: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

This way, each Github release is automatically attributed a DOI, and a permanent DOI that encompasses all releases is also generated. It lets users get an clean `BibTeX` entry to cite `MAD-X`.

Would you consider this integration?

**Comment by rdemaria** [comment]
Thanks! I activated the option of zenodo, next release should automatically get a doi. I have to figure how to add an old release...

**Comment by fsoubelet** [comment]
That's great!

As far as I know, it is not possible to create DOIs for releases older than the integration date between the two services.

However, Zenodo also generates a DOI that covers **all** versions. You can find it at the bottom right of the page. Attached is an example screeshot from the page of `tfs-pandas`. I think this should do the trick for most `MAD-X` citations.

<img width="1506" alt="Screenshot 2022-05-18 at 14 03 00" src="https://user-images.githubusercontent.com/19598248/169034331-ad8d2c33-e483-4000-abe9-7ffc5d2712db.png">

**Comment by rdemaria** [comment]
https://zenodo.org/record/7900976
