### ISSUE TITLE
In ptc_twiss, translation breaks higher-order calculations

### ISSUE THREAD

**Issue by jsberg-bnl** [MethodicalAcceleratorDesign/MAD-X#1110]
See this example: [220523b.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/8754688/220523b.txt)
There are two lines, the first having a translation and a drift, the second with just a drift, but with an initial condition that should give identical behavior to the case using the translation. At the end of either line, x should be 0. You can see that the initial conditions upon entering the drift are identical for both cases. But the case with the translation gets the wrong answer, it appears to do only the first order calculation. It looks like in the case with translation, either EXACT got turned off or the order got reduced to 1 (if you check the math you'll see that for the case with translation, the change in x is just px*o->l).

**Comment by rdemaria** [comment]
It looks ok, but I cannot double-check now. I am waiting Laurent or Piotr to comment the PR in the next few days, if none I will merge!

**Comment by ldeniau** [comment]
try with exact_mis=true in ptc_setswitch.

**Comment by jsberg-bnl** [comment]
exact_mis has no effect on the results.
