### ISSUE TITLE
SECTORMAP discrepancy

### ISSUE THREAD

**Issue by bogomyag** [MethodicalAcceleratorDesign/MAD-X#1112]
Using sectormap in twiss.

There is discrepancy with the manual, which says "The maps are the accumulated maps between the selected elements" in reality it is accumulated from the beginning of the lattice.

The second error is that sectorfile repeats the table twice, i.e. elements are repeated.
Here is an example script
[bug-1.zip](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/8759522/bug-1.zip)

Anton

**Comment by rdemaria** [comment]
I am not very experience here. Have you tried using:

```
select,flag=sectormap,clear;
select,flag=sectormap,class=monitor,COLUMN=NAME,POS,R11,R12,R21,R22,R33,R34,R43,R44,R16,R26;
```

?

**Comment by bogomyag** [comment]
Yes, Riccardo, I tried.
Result is the same.

**Comment by rdemaria** [comment]
I also remember that the behaviours was to get the maps in between selected elements. Like this

```
sxxxoxxxxxoxxxxoxxxxxoxxxxe
|   |     |    |     |    |
|-->|---->|--->|---->|--->|
   M1  o M2 o M3 o  M3 o M4 = OneTurnMap
```
where `o` are the selected elements... I will try to investigate, but it looks a bug to me.

**Comment by bogomyag** [comment]
Excluding `chrom` option from twiss eliminates repeating of the sectormap twice in the output file as Helmut suggested.

`twiss,betx=1,bety=1,file="twiss.tfs",sectormap,sectortable=my_sect_table,sectorfile="sector.tfs";`
produces map between the selected elements

`twiss,betx=1,bety=1,file="twiss.tfs",sectormap,SECTORACC,sectortable=my_sect_table,sectorfile="sector.tfs";`
produces accumulated map from the beginning.

The problem is solved
Thank you
