### ISSUE TITLE
In PTC_TWISS, row/column 5 entries for RE have the wrong sign.

### ISSUE THREAD

**Issue by jsberg-bnl** [MethodicalAcceleratorDesign/MAD-X#1120]
Just run this example: [220614a3.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/8910304/220614a3.txt). It executes several `PTC_TWISS` commands, uses them to compute the transfer map numerically, and compares it to the `RE##` entries in the `PTC_TWISS` table. All the entries correspond to a sign flip of variable 5 which I presume to be the MAD-X `T` variable.

**Comment by rdemaria** [comment]
I am not too familiar with  the conventions. Internally PTC uses -pt, -t as 5th and 6th coordinate, that is different sign and different position with respect to MAD. I think some effort was done to try to hide this, but I am not sure the implications for it. @piotrskowronski, what do you think?

**Comment by jsberg-bnl** [comment]
I think it actually uses pt and -t as its coordinates. You see it take care of this for the orbit in this block of code, note the sign flip for the time variable:
```
      ! swap t and pt
      myx=opt_fun(6)
      opt_fun(6)=opt_fun(5)
      opt_fun(5)=-myx
```
The problem is the same was not done for the output of the `RE` entries for the table. I'm unsure of how many other places this might be an issue. I've made a pull request that at least fixes the `RE` output for common `PTC_TWISS` cases, though there could be other issues (for example, if you provide an initial `RE` to `PTC_TWISS`, or for other PTC algorithms).

**Comment by jsberg-bnl** [comment]
I closed the pull request because something was wrong in one of the tests. I'll make a new pull request once I've figured out what is going on.

**Comment by jsberg-bnl** [comment]
OK, I found the bug and re-opened the pull request.

**Comment by jsberg-bnl** [comment]
I updated the pull request with code to fix the signs for the `initial_matrix_manual` case.

**Comment by jsberg-bnl** [comment]
Updated the pull request to handle `ptc_select` output. If I understand correctly, time is not tracked for `icase=5`, so I don't need to handle the code path with `c_%npara` not being 6 here:
https://github.com/MethodicalAcceleratorDesign/MAD-X/blob/6cfd5626f9cc3b411c17e0a92182591876be894e/src/madx_ptc_knobs.f90#L196-L205

**Comment by jsberg-bnl** [comment]
I added test suite updates to the pull request. I've checked that the only changes were the expected sign flips.
