### ISSUE TITLE
cpymad build test fails for macos

### ISSUE THREAD

**Issue by rdemaria** [MethodicalAcceleratorDesign/MAD-X#1124]
See:

 https://github.com/MethodicalAcceleratorDesign/MAD-X/runs/6940017710?check_suite_focus=true#step:6:22

Not sure why, I tried quickly to compare the building script from https://github.com/hibtc/cpymad/tree/master/.github but I could not spot differences.

Maybe @coldfix knows?

**Comment by coldfix** [comment]
Couldn't spot the problem from a quick look. I might have more time next week, but I don't know much about Mac.

**Comment by rdemaria** [comment]
@ldeniau could you have a look? Is GCC not usable with M1?

**Comment by ldeniau** [comment]
GCC does not support M1 also called arm64 arch. Only Apple Clang/LLVM support M1.

For GCC, it is a separate branch under development that will be merged for the first time in GCC 13. See https://github.com/iains/gcc-darwin-arm64 for more details.

To compile and run GCC, MAD-X, etc. on M1, compile as for Intel architecture e.g. x64_86 and use Rosetta2 to translate on-the-fly the binaries. If Rosetta is installed and you have Brew installed, you just have to run
`arch -x86_64 /usr/local/bin/brew`
in a terminal and everything will be run as-if you were on an Intel platform.

**Comment by rdemaria** [comment]
Fixed
