### ISSUE TITLE
Undefined variable used in radiation calculation for solenoid ends in tracking

### ISSUE THREAD

**Issue by jsberg-bnl** [MethodicalAcceleratorDesign/MAD-X#1128]
`const` in this line https://github.com/MethodicalAcceleratorDesign/MAD-X/blob/371026b256814a7cf22b1534ec719396cb5d2e15/src/trrun.f90#L3526 is not defined along this code path. Similarly for the zero length case above this.

**Comment by rdemaria** [comment]
solved by #1169
