### ISSUE TITLE
Unable to use tracking when sequence contains `refer=entry` or `refer=exit`

### ISSUE THREAD

**Issue by ab-gh** [MethodicalAcceleratorDesign/MAD-X#1132]
I'm attempting to run particle tracking on some lattices provided by CERN for the [PS slow extraction](https://gitlab.cern.ch/acc-models/acc-models-ps/-/tree/2022/scenarios/east/4_slow_extraction), which requires thin optics. When using makethin on the linked models, I get the warning:
```
++++++ warning: REFER in lattice must be set to CENTER, MAKETHIN: ignored
```
which is likely referring to [these PS sector sequences defined with `refer=entry`](https://gitlab.cern.ch/acc-models/acc-models-ps/-/blob/2022/ps_ss.seq#L703). MADX then ignores these sequences, and the tracking cannot begin.

How do I overcome this? Is there something I can adjust to allow `makethin` for `refer!=center`, or must I change the model/sequences in question?

**Comment by HelmutCERN** [comment]
Just save the sequence before calling MAKETHIN. This should translate the sequence to standard conventions. For me the following worked :
use, sequence=PS;
save,sequence=PS,file="ps.seq";
use, sequence=PS;
makethin,sequence=PS;

**Comment by ab-gh** [comment]
Thanks Helmut, this resolved my issue
