### ISSUE TITLE
Multiple Fringes on exit of magnet in PTC

### ISSUE THREAD

**Issue by jgray-19** [MethodicalAcceleratorDesign/MAD-X#1135]
When calling ptc_twiss, using the DKD model, two multipole fringes are performed on the exit of the magnets. This occurs within the function `fringe_STREX` and so a potential fix could be to comment out the following line. 
https://github.com/MethodicalAcceleratorDesign/MAD-X/blob/45b3401d9cf178a5fab44879461c09a8f2fcf073/libs/ptc/src/Sh_def_kind.f90#L14245

**Comment by rdemaria** [comment]
It looks like it is a duplication of https://github.com/MethodicalAcceleratorDesign/MAD-X/blob/45b3401d9cf178a5fab44879461c09a8f2fcf073/libs/ptc/src/Sh_def_kind.f90#L14239 right?

**Comment by rdemaria** [comment]
It looks like it is already fixed upstream: https://github.com/jceepf/fpp_book/blob/master/fpp_ptc/Sh_def_kind.f90#L14250

**Comment by jgray-19** [comment]
I think that the line is here instead:
https://github.com/jceepf/fpp_book/blob/aa574c37ab7a9f36fa59cc3b99f03bd7a5da1e29/fpp_ptc/Sh_def_kind.f90#L14267

**Comment by rdemaria** [comment]
yes you are right!

**Comment by jgray-19** [comment]
This has been fixed in #1200
