### ISSUE TITLE
New SBEND maps in PTC is not better.

### ISSUE THREAD

**Issue by ldeniau** [MethodicalAcceleratorDesign/MAD-X#1165]
There is clear evidence that the new SBEND map uses equations that brings more instabilities than the old one and not only for very small angles. To restore the use of the old map, set
logical :: old_thick_bend = .true.
in the file Sh_def_kind.f90 (around line 170)
Ideally, this could be a flag set at runtime by ptc_setswitch (many examples in the code use this approach).

**Comment by ldeniau** [comment]
Here is a slide showing that an input difference of 1.14e-16 (~ 1 eps) in a single monomial between the two codes (PTC and MAD-NG) leads to a difference of 1e-8 to 1e-7 on the resulting map.
[sbend map pb.pdf](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/10934769/sbend.map.pb.pdf)

**Comment by rdemaria** [comment]
Addressed by #1175
