### ISSUE TITLE
in tttdipole if angle ≠ k0l, k0 is added twice

### ISSUE THREAD

**Issue by szymonlopaciuk** [MethodicalAcceleratorDesign/MAD-X#1181]
In the circumstance that `angle != k0 * length`, and in particular if `angle = 0` and `k0 != 0`, in the following lines in `tttdipole` [(source)](https://github.com/MethodicalAcceleratorDesign/MAD-X/blob/a509a098c209ad33cbc8f31ec56183a85ebb3006/src/trrun.f90#L4666) we can have a situation where `k0 := 2 * k0`:

```fortran
  !---- Apply errors
  f_errors = zero
  n_ferr = node_fd_errors(f_errors)
  if (k0.ne.0) then
    f_errors(0) = f_errors(0) + k0*length - angle
  else
    k0 = h
  endif

  k0 = k0 * (one + ktap) ! tapering to main field only
 
  k0 = k0 + f_errors(0) / length ! dipole term
  k1 = k1 + f_errors(2) / length ! quad term
```

**Comment by rdemaria** [comment]
`test-twiss-15/test-twiss-15.madx` does tot test for track
