### ISSUE TITLE
JACOBIAN computes wrongly the Jacobian matrix.

### ISSUE THREAD

**Issue by ldeniau** [MethodicalAcceleratorDesign/MAD-X#1209]
The delta-h applied to the knobs is not independent between finite difference iterations as shown in the attached file, rolling over two variables at the same time that makes correlated moves. I am not aware of any such "combined" evaluation using two variables at the same time. The matrix obtained this way is probably "close to" the Jacobian, but it is not the Jacobian matrix...
[jacbug.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/13601594/jacbug.txt)

**Comment by rdemaria** [comment]
If your second column, is the diff between calls, it works as expected. See this simple example:

```
x1=0;x2=0;
match,use_macro;
vary,name=x1;
vary,name=x2;
mm: macro={
    y1=2*x1+3*x2;
    y2=4*x1+5*x2;
    value,x1,x2;
};
constraint,expr= y1=1;
constraint,expr= y2=2;
jacobian,calls=1,strategy=2;
jacobian,calls=1;
endmatch;
value,y1,y2;
```

```JACOBIAN:
Node       Constraint   Variable           Derivative
---------------------------------------------------------------
  mm             y1=1         x1     2.0000000000e+00
  mm             y1=1         x2     3.0000000000e+00
  mm             y2=2         x1     4.0000000000e+00
  mm             y2=2         x2     5.0000000000e+00
```

**Comment by ldeniau** [comment]
This is not a bug, but it seems that JACOBIAN is calling the macro twice consecutively with the same input values at the end of each "full iteration" (once finite differences are done), which is a waste of computation: same input, same output...
