### ISSUE TITLE
Add chromatic components in PTC_twiss

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#128]
*Issue migrated from trac ticket # 128*

**component:** ptc_twiss | **priority:** major
___
#### 2012-02-08 17:43:36: miriam.fitterer commented

date: 2012.02.01, From F. Schmidt
Many features are barely tapped into concerning PTC and one could easily calculate chromatic components from specific elements or element classes. I have been fighting together with Jean-Luc to start getting those items into ptc_twiss but this is by far not finished. We now have useful global parameters like second and third order momentum compaction but we also must get much better with the local parameters.

I propose that a rigorous effort shall be started to:

- specify those needs
- understand how to get it from PTC
- implement it.

Moreover, some of that could be implemented into TWISS as well.
___
#### 2012-02-09 14:00:42: @ldeniau commented

date: 2012.02.09, L. Deniau on behalf of M. Fitterer
Miriam added very valuable information and direction for this task

Short request proposal:
- Local and global list of contributions to the second order chromaticity especially the off-momentum beta-beating

Long version with explanations:
The theory about the contribution to the second order chromaticity was written down by many I guess. In Madx the Montague functions "W" are implemented and calculated for each element, which were first defined by Montague (LEP note 165):

http://cdsweb.cern.ch/record/443342?ln=en

which gives the off-momentum beta-beating. The off-momentum beta beating often gives a large distribution to the second order chromaticity, so minimizing the "W" minimizes indirectly the second order chormaticity:

http://cdsweb.cern.ch/record/282841?ln=en

Beside minimizing the second order chromaticity one usually also tries to minimize the beta-beating at the IP. You can match in madx the "W", so that you have W(IP)=0, so no off-momentum beta beating at the IP. For more details, I had a look at the note from Stephane, which also focuses on the LHC (LHC project report 308):

http://cdsweb.cern.ch/record/403591?ln=en

and lists all contributions to the second order chromaticity.

I guess for further studies, one would like to have a list of all contributions (not only the off-momentum beta beating contribution) and also the location, so sth. like an "extended" Montague function feature. As I understood Ricardo in the meeting, Stephane (and him?) have written already a macro to calculate this in madx.

PTC does the analyses to my knowledge differently than madx. It obtains the higher order chromaticities and the anharmonicities (detuning with amplitude) through a normal form analysis of the one turn map (ptc_normal command), but this is pretty slow for the full sequence of a LHC size lattice.

___
#### 2013-08-20 11:22:31: @ldeniau changed owner from ** to *skowron*

___
#### 2013-08-20 11:22:31: @ldeniau changed status from *new* to *assigned*

**Comment by ldeniau** [comment]
Status of this issue?

**Comment by ldeniau** [comment]
This is a long standing issue without a clear direction to take. Both PTC and MAD-X (through macros) can do it, so we close this issue.
