### ISSUE TITLE
Select does not work on twiss sectormap

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#141]
*Issue migrated from trac ticket # 141*

**component:** core_select | **priority:** major
___
#### 2012-03-15 16:59:27: eliana@fnal.gov commented

date: 2012.02.27
I am trying to get the values of the transport map by using "sectormap", but I am not able of selecting the map elements I am interested on.
___
#### 2012-03-15 16:59:45: @ldeniau uploaded file [`map.lat`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/141/map.lat) (0.4 KiB)

___
#### 2012-03-15 16:59:53: @ldeniau uploaded file [`map.log`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/141/map.log) (1.3 KiB)

___
#### 2012-03-15 17:00:03: @ldeniau uploaded file [`sectormap`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/141/sectormap) (16.8 KiB)

___
#### 2012-03-15 17:00:46: @ldeniau changed component from *mod_twiss* to *core_select*

___
#### 2014-04-30 16:37:26: @ldeniau changed owner from ** to *ghislain*

___
#### 2014-04-30 16:37:26: @ldeniau changed status from *new* to *assigned*

___
#### 2015-02-19 12:06:39: alatina commented

This is a known issue with no simple fix. 

___
#### 2016-01-22 14:50:10: kyrsjo commented

I see the same issue: SELECT column seems to be ignored for sectormap. Selecting elements works as expected as long as no select column is used.

Example:
```
select, flag=sectormap, clear;
!select,flag=sectormap, column=NAME,POS,R;
select,flag=sectormap, pattern="^ACFCA";
select,flag=sectormap, pattern="^ACSCA";
select,flag=sectormap, pattern="^IP";
twiss,sectormap=true,chrom=true,sectorfile="SECTOR_B1_allcav.tfs";
```
This produces a file SECTOR_B1_allcav.tfs with all columns and only the selected elements. Including the commented-out select statement yields a sectormap with all elements and also all columns.

___
#### 2016-05-23 10:28:42: @ldeniau changed owner from *ghislain* to *ldeniau*

**Comment by tpersson** [comment]
A way to do this has been explained in PR #724
