### ISSUE TITLE
Proposal for tests and changes in the MADX code

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#172]
*Issue migrated from trac ticket # 172*

**component:** core_sequence | **priority:** major
___
#### 2012-07-18 13:10:51: stephane.fartoukh commented

date: 2008.12
Please find below a complete symplecticity and consistency check for single element
a)      defined by a 6D dX offset , R and T matrix
b)      defined with a linear or non-linear transfert map M: X0 à X=M(X0)

The things to be checked are

a) consistency
dX=M(X0=0)
R_ij = (dM_i/dX_j)_(X0=0)
T_ijk =1/2 (d2M_i/dX_j/dX_k)_(X0=0)

b) Symplecticity
transpose(R) * J * R =J
transpose (Tk) * J * R + transpose (R) * J * Tk =0  for k=1..6

where Tk is the 6*6 matrix defined by (Tk)_ij= Tijk and J is the usual 2 by 2 block diagonal symplectic matrix with the blocks [[0,1],[-1,0]] on the diagonal.

From laurent.deniau
I added the attached document gently provided by Stephane for history and backup. The tests above where used to test the RF-multipoles of Andrea. Other points like sequence reflector will be studied in some future.

___
#### 2012-07-18 13:12:15: @ldeniau uploaded file [`beam2-beam4.doc`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/172/beam2-beam4.doc) (76.0 KiB)

___
#### 2015-09-11 10:49:55: @ldeniau commented

This improvement requires careful check of the code in twiss. This could be done step by step as the elements are reviewed and cleaned (or moved to the new MAD). LD.

___
#### 2015-09-11 10:49:55: @ldeniau set owner to *alatina*

___
#### 2015-09-11 10:49:55: @ldeniau changed status from *new* to *assigned*

**Comment by ldeniau** [comment]
Optimised routines exist in MAD-NG. We may import them in MAD-X such that with proper flags, the checks could be done after each element and before concatenation of the maps.

**Comment by rdemaria** [comment]
Good ideas, but  I am closing now as it is a project in itself. Happy to reopen when somebody finds the time.
