### ISSUE TITLE
Invalid calculation in the dynap module

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#181]
*Issue migrated from trac ticket # 181*

**component:** mod_dynap | **priority:** major
___
#### 2012-10-16 14:10:42: emanuel.karantzoulis@elettra.trieste.it commented

date: 2012.10.05
The version MAD8 I have it was uploaded from the CERN site:  MAD8 for Windows. For MAD-X I would like to sort out the dynamic aperture problem, as I told you before for some reason  the dynapfrac comes always zero and I get tune shifts in the tracking that are very big whereas this is not the case when I treat the same file with MAD8. I know the results of MAD8 are correct because I compare them with the machine. I am quite happy with mad8 its only problem is that it does not calculate coupling related beam parameters for a non flat machine, so when I introduce skew quads this part of calculations does not exist. It would have been very nice if MADX could do it or an enhanced version of MAD8, but I think before that it has to be understood the dynap inconsistency.
___
#### 2012-10-16 14:11:37: @ldeniau uploaded file [`Elettra_test.txt`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/181/Elettra_test.txt) (2.1 KiB)

___
#### 2012-10-16 14:11:47: @ldeniau uploaded file [`Elettra_lattice.txt`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/181/Elettra_lattice.txt) (5.3 KiB)

___
#### 2012-10-16 14:12:04: @ldeniau uploaded file [`outputfile.txt`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/181/outputfile.txt) (62.8 KiB)

MAD8 output

___
#### 2012-10-17 14:48:24: @ldeniau commented

date: 2012.10.17
A minimal example has been provided by emanuel.karantzoulis, see new attached files

___
#### 2012-10-17 14:48:48: @ldeniau uploaded file [`Elettra_example_min.txt`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/181/Elettra_example_min.txt) (1.9 KiB)

___
#### 2012-10-17 14:49:00: @ldeniau uploaded file [`Elettra_lattice_min.txt`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/181/Elettra_lattice_min.txt) (4.0 KiB)

___
#### 2012-10-17 14:49:16: @ldeniau uploaded file [`echo_elettra.txt`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/181/echo_elettra.txt) (4.1 KiB)

___
#### 2012-10-17 14:49:27: @ldeniau uploaded file [`dynap0_elettra.txt`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/181/dynap0_elettra.txt) (1.1 KiB)

___
#### 2012-10-17 14:49:33: @ldeniau uploaded file [`dynaptune0_elettra.txt`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/181/dynaptune0_elettra.txt) (0.5 KiB)

___
#### 2012-10-17 14:52:28: @ldeniau uploaded file [`twiss1_out.txt.gz`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/181/twiss1_out.txt.gz) (131.0 KiB)

___
#### 2012-10-17 14:53:00: @ldeniau commented

date: 2012.10.17
A minimal example has been provided by emanuel.karantzoulis, see new attached files starting from Elettra_example_min.txt

___
#### 2012-12-04 14:35:24: @ldeniau commented

date: 2012.12.04, from laurent.deniau
A first attempt to look at the problem does not give much idea where the problem is coming from. It is not clear either if the warnings are expected or not by the user and if the implications are well understood
 ++++++ warning: TWCPGO: TWISS uses the RF system or synchrotron radiation only to find the closed orbit, for optical calculations it ignores both.

___
#### 2012-12-04 14:35:24: @ldeniau changed owner from ** to *ioannis.papaphilippou*

___
#### 2012-12-04 14:35:24: @ldeniau changed status from *new* to *assigned*

___
#### 2015-07-08 18:04:01: ghislain commented

Dynap cleaning in progress: 

- DYNAPFRAC is initialized at zero and never updated anywhere.

The observed behavior is therefore understood. But is it correct ?  

___
#### 2016-05-23 10:24:17: @ldeniau changed owner from *ioannis.papaphilippou* to *ldeniau*

**Comment by tpersson** [comment]
I had a look at the DYNAP module and it is simply not doing any calculations of the limit of the DA. The footprint has been validated several times and everything there looks fine to me. I would remove the DYNAPFRAC and at the same time add the start coordinates

**Comment by tpersson** [comment]
The calculation of the DYNAPFRAC is never filled and is now removed in #853. The rest of the calculations looks correct so I will close the issue.
