### ISSUE TITLE
Vertical beta function in PTC Twiss

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#186]
*Issue migrated from trac ticket # 186*

**component:** ptc_twiss | **priority:** major | **keywords:** ptc_twiss, beta22
___
#### 2012-11-09 17:33:04: Piotr.Skowronski@cern.ch commented

A bump is modeled with 3 different ways. They shall give a priori the same results, however, vertical beta function is different. Reported by Olav Berrig:

However, I added the vertical optical functions (alfa and beta) and I noticed that they are different (see below), in each of our three test cases. These calculations were done in a slightly modified program: http://info-afs-berrig.web.cern.ch/info-afs-berrig/public/programs/MAD/Test_BT_line_3/

So if you agree, we will close this ticket and I will open another ticket. Do you agree?

The new ticket will state that the vertical alfa and beta and are not equal (as they should be) for the two cases:

2.       Bend(field error), Quad, Bend(field error)

3.       Kicker, Quad, Kicker

The first case: Bend, Combined Bend/Quad, Bend , furthermore, gives values for the vertical alfa and beta that are so different from the two other case, that it might interesting to investigate it. Of course this first case is different (according to what you explained that the quadrupole strength is changed to make the bending angle correct) so maybe it is natural?
___
#### 2012-11-09 17:34:37: Piotr.Skowronski@cern.ch uploaded file [`test_bt_line.madx`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/186/test_bt_line.madx) (13.3 KiB)

___
#### 2012-11-09 17:35:08: Piotr.Skowronski@cern.ch changed owner from ** to *skowron*

___
#### 2012-11-09 17:35:08: Piotr.Skowronski@cern.ch changed status from *new* to *assigned*

___
#### 2012-11-12 12:54:09: @ldeniau changed component from *_build* to *ptc_twiss*

**Comment by ldeniau** [comment]
Still valid?

**Comment by piotrskowronski** [comment]
The kicker does not have fringe fields, while rbend and quad do. Switching off the fringe fields everywhere brings the results close:
"Bend w/bfield err - Quad w/pos error" is identical to "KCK -  Q displaced  - KCK"
The option Bend - comb fun bend" is 10% off because the bend length and orbit is not identical in this case.

**Comment by piotrskowronski** [comment]
For reference, attached the modified madx script with the fringe fields off.


[test_bt_line.madx.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/1362100/test_bt_line.madx.txt)
