### ISSUE TITLE
ptc_twiss table is not filled with variable from ptc_select

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#256]
*Issue migrated from trac ticket # 256*

**component:** ptc_twiss | **priority:** major
___
#### 2014-02-28 07:12:00: bogomyag commented

I tried to add elements of second order matrix from ptc_select to table created by ptc_twiss. The first time I run ptc_twiss the variables are added but the values are zero, after the second run the values are correct.
___
#### 2014-02-28 07:12:44: bogomyag uploaded file [`chicane.madx`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/256/chicane.madx) (4.6 KiB)

MADX script

___
#### 2014-02-28 07:13:06: bogomyag uploaded file [`madx.ps`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/256/madx.ps) (42.1 KiB)

PLOT results

___
#### 2014-04-30 15:17:07: @ldeniau changed owner from ** to *skowron*

___
#### 2014-04-30 15:17:07: @ldeniau changed status from *new* to *assigned*

**Comment by tpersson** [comment]
I just checked the example and it looks to me that the select is working correctly so I will close this issue.
