### ISSUE TITLE
fort.18 from ptc_twiss and ptc_normal docu

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#269]
*Issue migrated from trac ticket # 269*

**component:** ptc_twiss | **priority:** minor | **keywords:** transfer map, fort.18
___
#### 2014-06-06 11:58:07: Piotr.Skowronski@cern.ch commented

Document and clarify fort.18 file with transfer map

___
#### 2016-09-30 14:59:49: @ldeniau changed status from *new* to *assigned*

**Comment by ldeniau** [comment]
This file is for experts only, either the content is obvious to the user or it should not be considered at all...
