### ISSUE TITLE
Tracking through a PTC produced map. Map manipulation tools.

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#294]
*Issue migrated from trac ticket # 294*

**component:** ptc_module | **priority:** major
___
#### 2014-08-27 17:21:35: Piotr.Skowronski@cern.ch commented

Request from Frank Schmidt.

The MADX implementation of DA tools that are used currently as stand alone tools. 

The use case:
 - Run normal form, but allow some extra options to save the map in the memory
 - a new command will allow to perform advanced normal forms, 
   for example leaving many rosonases in, keep decomposed A_ A_*, rot, J and G for further operations
 - a command will let to concatenate, invert and possibly apply other operation to the maps that are stored in the memory, and also dump result to file
 - a spacial tracking command that applies a named map to set of coordinates defined in ptc_start 
 

___
#### 2016-09-30 14:24:09: @ldeniau changed status from *new* to *assigned*

**Comment by ldeniau** [comment]
This issue is kept open, but requires significant work and ressource not available. Moreover, next generation of MAD application (under development) has these features.

**Comment by ldeniau** [comment]
After few years, we still don't have the resource to handle such development. BTW the last requested item is already possible with PTC_TRACK and Normal forms.
