### ISSUE TITLE
Change of definition of offset files for aperture: move to sequence data

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#301]
*Issue migrated from trac ticket # 301*

**component:** mod_aperture | **priority:** major | **keywords:** sequence offset
___
#### 2014-09-17 19:36:07: ghislain commented

Request from R. De Maria, 29/8/2014 @ MAD_X meeting:

Aperture not centered on the reference trajectory can be displaced by a file called offset that contains one reference node that defines the reference frame of the displacement vector. 

Displaced element has a x,x’,x’’,y,y’,y’’ parameters that are components of the vector that displace the center of the aperture as a function of s in the reference frame of the reference node.

Issues:
• The offset files are not generated by the layout database. The offset data cannot be in the sequence file. Offset data cannot be parametric.
• Offset data depends on the sequence in which common elements are installed (it is not a simple property, but a sequence dependent property.)
• For offsets in the arc (e.g 11T dipoles) is not practical have a reference node in the straight section, but it practical that the offset itself is defined in the reference frame of the center of the element.
• For elements in the straight section is not practical to have in the center of the element itself, but from the IP or as of now from the s.ds.l[12345678].b[12].

Proposal:
• Define in the sequence definition the reference node and offset data each element whose aperture needs to be displaced and the aperture offsets.
• Define in seqedit the commands to change this data.
___
#### 2014-09-17 20:13:19: ghislain commented

The OFFSETELEM attribute affects only the APERTURE command (n1 calculation) and not the TRACK command where another, so far undocumented, mechanism exists: 

An element definition or instantiation, ie within a sequence declaration, can take a parameter APER_OFFSET={xoff,yoff} where xoff and yoff are real values and are offsets of the element aperture. These parameters are taken into account when evaluating whether the particle is still within the physical aperture. 

Depending on your need, can you please clarify whether this feature satisfies your request or not, ie whether the request applies to APERTURE command or TRACK command ?  

Ghislain 

___
#### 2014-09-17 20:13:19: ghislain changed owner from ** to *ghislain*

___
#### 2014-09-17 20:13:19: ghislain changed status from *new* to *assigned*

___
#### 2016-05-23 10:07:09: @ldeniau changed owner from *ghislain* to *alatina*

___
#### 2016-05-23 10:07:29: @ldeniau changed owner from *alatina* to *ldeniau*

**Comment by ldeniau** [comment]
Status of this issue?

**Comment by tpersson** [comment]
This has been fixed
