### ISSUE TITLE
PTC track: different coordinate system between time=false and time=true

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#321]
*Issue migrated from trac ticket # 321*

**component:** ptc_track | **priority:** major
___
#### 2015-01-16 22:13:57: ahuschau commented

Dear Piotr,

As discussed today please find attached some files to reproduce the following issue:
Using the lattice of the PS in the MADX repository I would like to understand the conversion between the longitudinal coordinates when either using time=false or time=true when tracking with the ptc_track command.
The attached PDF files should explain my problem a bit more clearly: When tracking with time=true the energy coordinate is supposed to be dE/pc. Then I would expect that one needs to multiply by the factor pc/(E*betarel^2) to obtain dp/p. This should then be equal to the output of the tracking with time=false, but it isn't (see PTC_track_time_comparison.pdf). 
Furthermore, plotting both cases for 2500 turns reveals that the synchrotron period is different (see PTC_track_time_false.pdf and PTC_track_time_true.pdf).
It might be, as you mentioned, that it is related to the s coordinate (pathlength or ct). I think that the difference here would only come from the betarel, which is 0.99, so I don't see how this could cause the problem.

Any idea about the correct conversion between the two different settings for time?

Thanks a lot and cheers,
Alex

PS: I added the seqedit in the input script as the cavity definition without no_cavity_totalpath, as it is done within the lattice, leads to a longitudinal motion, which is not centered around zero (see PTC_track_wo_no_cav_totalpath.pdf). Is this always required or am I missing something here?

___
#### 2015-01-16 22:14:39: ahuschau uploaded file [`mte_ptc_track.madx`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/321/mte_ptc_track.madx) (0.9 KiB)

___
#### 2015-01-16 22:14:50: ahuschau uploaded file [`PTC_track_time_comparison.pdf`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/321/PTC_track_time_comparison.pdf) (12.7 KiB)

___
#### 2015-01-16 22:14:57: ahuschau uploaded file [`PTC_track_time_false.pdf`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/321/PTC_track_time_false.pdf) (6.2 KiB)

___
#### 2015-01-16 22:15:03: ahuschau uploaded file [`PTC_track_time_true.pdf`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/321/PTC_track_time_true.pdf) (6.1 KiB)

___
#### 2015-01-16 22:15:09: ahuschau uploaded file [`PTC_track_wo_no_cav_totalpath.pdf`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/321/PTC_track_wo_no_cav_totalpath.pdf) (8.6 KiB)

___
#### 2015-01-16 22:17:44: ahuschau changed component from *_build* to *ptc_track*

___
#### 2015-01-16 22:20:54: ahuschau changed type from *defect* to *info*

___
#### 2015-06-22 09:02:47: @ldeniau changed owner from ** to *skowron*

___
#### 2015-06-22 09:02:47: @ldeniau changed status from *new* to *assigned*

___
#### 2017-03-13 14:20:40: Piotr.Skowronski@cern.ch 

___
#### 2017-03-13 14:20:40: Piotr.Skowronski@cern.ch commented

Dear Alex,

The equation to go from pt # dE/pc(E-E0)/(E0 betareal0) to deltap = (p - p0)/p0 is following

pt = sqrt( (1+deltap)^2^ + (1-betarel0^2^)/betarel0^2^) - 1/betarel0

betarel0 is the relativistic beta corresponding to E0 (or p0)

Does it fit when you use this equation?

Piotr

**Comment by piotrskowronski** [comment]
Not hearing for half a year any answer from the user I close the issue.
