### ISSUE TITLE
EMIT wrongly calculates emittances and U0

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#341]
*Issue migrated from trac ticket # 341*

**component:** mod_emit | **priority:** major | **keywords:** emittance energy loss
___
#### 2015-05-18 11:28:56: ghislain commented

Reported on 15 May 2015 by Andreas Doblhammer

Comparison between MAD-X and ELEGANT shows that the synchrotron radiation integrals calculated by "Twiss, chrom" in MAD-X matches those of ELEGANT. Consequently the derived Jx and emittances match as well. 

However the EMIT module in MAD-X disagrees with ELEGANT for the calculation of emittances and energy loss per turn. It looks like the synchrotron radiation integrals could be wrongly calculated by EMIT. 

Reminder: EMIT has its own twiss calculation! 
 
___
#### 2015-05-19 16:50:07: ghislain commented

News from Andreas: MAD8 has two modules to calculate U0: BEAMPARAM gives values equal to those of ELEGANT and those derived from MADX/TWISS. EMIT in MAD* gives same values as EMIT in MADX, which does not fit those of ELEGANT and those derived from MADX/TWISS. 

News from Ghislain: The calculation of U0 in MADX/EMIT is based not on the energy loss in individual elements but on the energy gain in the RF cavities. See line 806 of emit.f90: 
  sumu0 = sumu0 + rfvlt * sin(rflag - rffrq * time)

Since MADX/TWISS seems to be correct in the evaluation of radiation synchrotron integrals, one could think of deriving other paramaters from the same TWISS module and foregoing the EMIT module altogether. The workload and consequences should be evaluated and presented at a MADX meeting for decision. 

___
#### 2015-05-19 16:50:07: ghislain changed owner from ** to *ghislain*

___
#### 2015-05-19 16:50:07: ghislain changed status from *new* to *assigned*

___
#### 2016-05-23 09:56:42: @ldeniau changed owner from *ghislain* to *irina.shreyber*

___
#### 2016-11-11 16:05:08: shreyber changed owner from *irina.shreyber* to *nobody*

**Comment by tpersson** [comment]
Is this still something we should look into or is this fixed?
