### ISSUE TITLE
Add marker at the beginning and end of a sliced element with makethin

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#347]
*Issue migrated from trac ticket # 347*

**component:** mod_mkthin | **priority:** major
___
#### 2015-06-01 14:39:18: rdemaria commented

Add an option in makethin such that a marker positioned at the beginning and the end of the element is inserted in addition to the marker at the center of the element. Make sure that aperture and mech_sep attributes are copied.

This feature is useful to have a consistent aperture model also for thin optics.

___
#### 2015-06-22 08:59:38: @ldeniau changed owner from ** to *hburkhardt*

___
#### 2015-06-22 08:59:38: @ldeniau changed status from *new* to *assigned*

___
#### 2015-11-03 16:06:14: @ldeniau commented

date: 2015.11.03, from ldeniau
Ghislain implemented this feature as part of the export of aperture markers to sixtrack. Does it still make sense to implement these surrounding markers in makethin?

**Comment by ldeniau** [comment]
These features are normally implemented, still waiting from users to know if it has expected behaviour.

**Comment by tpersson** [comment]
This was actually already fixed before but is also in #743
