### ISSUE TITLE
Improvements on aper_offset

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#353]
*Issue migrated from trac ticket # 353*

**component:** mod_aperture | **priority:** major | **keywords:** aperture offset tilt
___
#### 2015-06-24 11:38:24: rdemaria commented

aper_offset will start to be used to model aperture in thin sequences. The following new features will be needed:

- allow aper_offset to be taken into account in the aperture module
- allow aper_offset values to be in the twiss table output like aper_1, aper_2, etc,
- introduce a tilt angle attribute (e.g. 3rd valued in aper_offset or something equivalent)

___
#### 2015-08-04 11:06:03: ghislain commented

Replying to [#353 rdemaria]:
> aper_offset will start to be used to model aperture in thin sequences. The following new features will be needed:
> 
> - allow aper_offset to be taken into account in the aperture module

This requires a bit more thoughts regarding how this is articulated with the aperture offset specifications given via the OFFSETELEM attribute of the APERTURE command: would APER_OFFSET replace or be added to OFFSETELEM ? 

> - allow aper_offset values to be in the twiss table output like aper_1, aper_2, etc,

This can be added; it was not in the output so far because it was used only in tracking.

> - introduce a tilt angle attribute (e.g. 3rd valued in aper_offset or something equivalent)

This also requires more thoughts. If APER_OFFSET is a purely linear effect, then having the angle as third value is fine.
Another possibility is to add an APER_TILT parameter. 

To be discussed at a MAD-X meeting to clarify the specs. 

___
#### 2015-08-04 11:06:03: ghislain changed owner from ** to *ghislain*

___
#### 2015-08-04 11:06:03: ghislain changed status from *new* to *assigned*

___
#### 2015-08-04 14:07:33: ghislain commented

I have implemented the reading of aperture offsets from each element in the aperture command. The aperture offset is then used in conjunction with the OFFSETELEM data by simple addition. XOFFSET and YOFFSET have been added to the list of available columns in aperture table. 

Commit is pending review and further discussions in a MAD-X meeting.

___
#### 2016-05-23 10:41:48: @ldeniau removed owner (was *ghislain*)

___
#### 2016-09-30 14:26:40: @ldeniau set owner to *nobody*

**Comment by madcern** [comment]
This is all there and seems to be working fine
