### ISSUE TITLE
switch the BB induced closed-orbit on or off in PTC

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#362]
*Issue migrated from trac ticket # 362*

**component:** ptc_proper | **priority:** major | **keywords:** PTC, beam-beam, bb
___
#### 2015-09-01 15:12:29: Piotr.Skowronski@cern.ch commented

I used the bborbit flag from MAD-X so that I can
switch the BB induced closed-orbit on or off. This represents
an "illegal" coupling between MAD-X and PTC and has to be
dealt with in a proper way within PTC.

Both these changes have to be reviewed by Piotr together
with Etienne. 
___
#### 2015-09-01 15:13:13: Piotr.Skowronski@cern.ch uploaded file [`Sma0_beam_beam_ptc.f90`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/362/Sma0_beam_beam_ptc.f90) (15.5 KiB)

PTC source file with modification

___
#### 2015-09-01 15:15:44: Piotr.Skowronski@cern.ch changed owner from *frank.schmidt@cern.ch* to *skowron*

___
#### 2015-09-01 15:15:44: Piotr.Skowronski@cern.ch changed status from *new* to *assigned*

___
#### 2015-09-01 15:17:51: Piotr.Skowronski@cern.ch commented

Reported bu Frank Schmidt

___
#### 2015-09-11 16:33:00: @ldeniau changed component from *_build* to *ptc_proper*

**Comment by tpersson** [comment]
Can we close this?

**Comment by ldeniau** [comment]
Without a clear answer in the status after 2 weeks, we prefer to close this issue.
