### ISSUE TITLE
ptc_normal with node tracking

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#363]
*Issue migrated from trac ticket # 363*

**component:** ptc_normal | **priority:** major
___
#### 2015-09-01 18:42:11: Piotr.Skowronski@cern.ch commented

Request from Frank Schmidt:

Hi,

The BB can be activated in ptc_twiss. What is missing is
to also get it to run in ptc_normal because I need to perform
NF with the inclusion of BB.

Cheers, FS

___
#### 2015-09-11 16:33:38: @ldeniau changed component from *_build* to *ptc_normal*

___
#### 2016-09-30 14:24:29: @ldeniau changed status from *new* to *assigned*

___
#### 2017-03-02 11:26:19: @ldeniau set resolution to *fixed*

___
#### 2017-03-02 11:26:19: @ldeniau changed status from *assigned* to *closed*

___
#### 2017-03-02 11:26:59: @ldeniau removed resolution (was *fixed*)

___
#### 2017-03-02 11:26:59: @ldeniau changed status from *closed* to *reopened*

___
#### 2017-03-02 11:27:40: @ldeniau commented

Need and extra routine to add in ptc_normal. Need some work.

**Comment by piotrskowronski** [comment]
Done.
