### ISSUE TITLE
6D beam-beam conversion to SixTrack

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#380]
*Issue migrated from trac ticket # 380*

**component:** fmt_6track | **priority:** major
___
#### 2015-11-11 18:11:50: rdemaria commented

The new SixTrack will need new quantities for each beam-beam element defined in madx to be transferred to SixTrack.

The quantities extend what is already present in the BEAMBEAM element
(SIGX, SIGY, XMA, YMA, CHARGE)

and need the full 6D sigma matrix, full orbit information of the strong beam and the number of slices: e.g SIGXXP, SIGXY, SIXXPYP, SIXT,... PXMA, PYMA, ..., SLICES.

The converted quantities should now appear fc.3.aux under the BEAM section in this format:

if slice==0

  name slice sigx sigy h-sep v-sep charge

else

  name slice xangle xplane h-sep v-sep
  sig_x-x sig_x-xp sig_xp-xp sig_y-y sig_y-yp
  sig_yp-yp sig_xy sig_xp-yp sig_y-yp charge

The definition of the new quantities in the madx should be discussed in more detail, in particular if a 6D beam-beam implementation will eventually be developed in madx. Based in the discussion, the conversion rules will be clarified. 

___
#### 2015-11-27 17:57:28: @ldeniau changed component from *_build* to *fmt_6track*

___
#### 2015-12-04 18:58:20: kyrsjo commented

Regarding the list of inputs (sig_x-x etc.), I think some may be missing? SixTrack reads 11 doubles after (not including) separy, into variables initially named mm1 to mm11. The first 10 (mm1 to mm10) are then copied into the parbe array. Furthermore, you list sig_y-yp twice...

Could you maybe update the BEAM block description in the Sixtrack manual / "JavierBB" branch?

___
#### 2016-09-30 14:25:12: @ldeniau set owner to *alatina*

___
#### 2016-09-30 14:25:12: @ldeniau changed status from *new* to *assigned*

___
#### 2016-12-15 13:02:22: @ldeniau commented

date: 2016.12.15
Sixtrack is going under a change of the beam beam element file format, so we wait stable status.

**Comment by ldeniau** [comment]
What is the status of this issue?

**Comment by ldeniau** [comment]
Not urgent, waiting for the wire implementation, and let's discuss it again...

**Comment by rdemaria** [comment]
I would leave it open, maybe flag as less urgent. SixTrack format is stable and it would still be useful to implement...

**Comment by ldeniau** [comment]
Ok, let's see what will come out in the next weeks.

**Comment by tpersson** [comment]
There will be a full review of to deal with the 6D beam-beam so I will close this issue.
