### ISSUE TITLE
aperture attributes in twiss tables

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#384]
*Issue migrated from trac ticket # 384*

**component:** mod_twiss | **priority:** major
___
#### 2016-01-21 16:27:17: rdemaria commented

Presently 

The twiss table can have the columns:

  aptol_1, aptol_2, aptol_3

See [[r1093](../commit/f5c9dd98c8e556a09068e161731af2f304b91ef5)](../commit/f5c9dd98c8e556a09068e161731af2f304b91ef5)

Those columns are called
 
  rtol, xtol, ytol 

in the aperture table.

Aperture table can also have

  xoffset and yoffset 

when #353 will be merged.

Can we have in both aperture and twiss:

  rtol, xtol, ytol, xoffset, yoffset

to have uniform names?

___
#### 2016-09-30 14:27:17: @ldeniau set owner to *nobody*

___
#### 2016-09-30 14:27:17: @ldeniau changed status from *new* to *assigned*

**Comment by ldeniau** [comment]
The PR has been accepted.
