### ISSUE TITLE
something strange happens when I extract a table with apertures before saving the sequence

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#409]
*Issue migrated from trac ticket # 409*

**component:** mod_aperture | **priority:** major
___
#### 2017-01-06 10:24:27: vera.chetvertkova@cern.ch commented

I've noticed something strange when saving a sequence in MADX.

I have a beamline file with apertures (CRYRING_CO_v1.1.opt) and when I save it as a sequence using the following script ("twiss", in the attachment):

use,sequence=CRYRING;
twiss, sequence=CRYRING;
save, sequence=CRYRING, file="CRYRING_CO_v1.1.seq";

everything works perfect.

However once I want to extract a table with apertures before saving the sequence ("twiss+aper"):

use,sequence=CRYRING;
twiss, sequence=CRYRING;
select, flag=aperture, column=name,s,aper_1,aper_2;
aperture,file="CRYRING_CO_v1.1.aper.tfs";
save, sequence=CRYRING, file="CRYRING_CO_v1.1+aper.seq";

something strange happens and the value e2 of the sbend gets set to zero (value e1 stays correct). As a consequence once I use this saved sequence file CRYRING_CO_v1.1+aper.seq nothing works.
I attach the scripts so you could have a look.
___
#### 2017-01-06 10:24:47: alatina uploaded file [`CRYRING_CO_v1.1.opt`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/409/CRYRING_CO_v1.1.opt) (14.6 KiB)

___
#### 2017-01-06 10:24:56: alatina uploaded file [`twiss`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/409/twiss) (0.3 KiB)

___
#### 2017-01-06 10:25:06: alatina uploaded file [`twiss+aper`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/409/twiss+aper) (0.4 KiB)

___
#### 2017-03-02 11:59:21: @ldeniau commented

ticket related to #377

**Comment by ldeniau** [comment]
This may be connected to issue #445. To be confirmed.

**Comment by tpersson** [comment]
I just ran this example and it does work correctly now. I checked which version it was fixed in and it was in  5.03.07.
