### ISSUE TITLE
Too much suppressed!

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#412]
*Issue migrated from trac ticket # 412*

**component:** ptc_twiss | **priority:** major
___
#### 2017-01-23 10:28:24: Piotr.Skowronski@cern.ch commented

Hi,

I am just playing with PTC and I still dislike very much
that quite crucial material is suppressed!

I know that this has been a request by Eberhard Keil but we all need
the most relevant data at low debuglevel and the less relevant data
at higher levels.

1) My problem in question is that to get the closed_orbit I need:

ptc_setswitch, debuglevel=2,...;

This very essential and is even printed out by default for TWISS!

2) And what is really annoying for me is the fact that the information
of "deviation from the sympleticity condition" is dropped altogether!

This is NOT irrelevant but makes sure even for the attentive
user that there isn't some small issue with the code. It shouldn't
but sometimes there is indeed!

3) On the other hand with debuglevel=2 the output is 4 times as
large which is highly undesirable and useless!

4) I therefore suggest:

a) plug  closed_orbit as a default or at least  for debuglevel=1
in ptc_setswitch.

b) De-clutter level debuglevel=2 in ptc_setswitch and plug these
excessive info to debuglevel=3 but leave a few interesting info
there and in particular give me back "the deviation from the
sympleticity condition" at that level.

Thanks for considering my request!

Cheers, FS

**Comment by ldeniau** [comment]
If I remember well, this is a non-issue. Just a matter of taste between different users want or not to have a lot of display on their terminal. Maybe a flag or debug level could help. To be discussed.
