### ISSUE TITLE
Interesting inconsistency in ptc_twiss!

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#413]
*Issue migrated from trac ticket # 413*

**component:** ptc_twiss | **priority:** minor
___
#### 2017-01-23 17:56:04: Piotr.Skowronski@cern.ch commented

Hi,

This is almost a "philosophical" comment! I have renewed
concerns about the 5D and 6D treatment in ptc_twiss.

I am not really asking for program changes but to reflect
about how it should truly be done. In fact, it might be
relevant even for the new MAD.

Normally the situation should be crystal clear:

1) 6D case: since this concerns the full motion in 3 degrees
of freedom the usual 5D concepts fall apart, i.e. there is no
such a thing as dispersion nor chromaticty in 6D. On the
other hand we truly need them for accelerator design, so
what to do?

2) 5D case, here pt (deltap/p) is seen as a parameter of the
4D case. Dispersion and chromaticity follow naturally via
the proper NormalForm.

3) Luckily, Etienne has chosen the 5th coordinate as
pt (deltap/p) and sigma as the 6th, although it does cause
considerable confusion and some weird but correct "-" signs,
since this is not the canonical choice of variables.

4) Due to a discussion I am having with my student I had
another careful look at a 6D map from the PS since it was
handy. When I do the straight forward (external) 6D
NormalForm there is neither dispersion nor chromaticity.
However since the 5D map is part of the 6D one I can of
course do a 5D NormalForm of the 6D map and now I get
readily both dispersion and chromaticity. So far so good!

5) Now doing ptc_twiss old or the most recent one I do get
dispersion but NOT the chromaticity! There is some
reasoning to this but in fact it is inconsistent!

One could imagine to do both but somehow indicate how
this is done. In fact, there is even another reason for that.
When you compare in detail the 2 ways to calculate the
dispersion from a 5D map proper, i.e. without the cavity
and using the 5D part of the 6D map with the cavity the
values for the dispersion are  usually not completely the
same. The reason for that is that I typically find a small
coupling between the longitudinal and horizontal plane
and most likely this causes the small difference.
Unclear what is the true dispersion?!?

My main worry is that people do not fully appreciate the
difference between 5D and 6D. Since MAD-X calculates
whatever can be conveniently be done this does not
become apparent. Therefore some thought would be
useful...

I leave it to you!

Cheers, FS 
___
#### 2017-01-23 17:56:18: Piotr.Skowronski@cern.ch commented

Dear Frank,

I am not sure what you would like me to implement.
6D dispersion is calculated using de Moivre - Ripken Ha matrices and assuming that longitudinal tune is much smaller from the transfers ones (stroboscopic average)

I need to read more and/or think if chroma can be evaluated a similar way. Do you propose to always run the 5D normal form on top the 6D one to get chroma and non-linear dispersions?

Best Regards,
Piotr 

___
#### 2017-01-23 17:56:29: Piotr.Skowronski@cern.ch commented

Excellent questions Piotr!

Let me explain:

1) In 6D there should be strictly neither a dispersion nor chromaticity! There is even
an ugly truth that both are only an approximation since the longitudinal plane will
couple to some extent into the transverse plane and that changes both compared to
the 5D case.

2) In 5D of course it must be there and there is zero issue here.

3) The problem with 1) is that people do NOT realize that this is an additional
service that is provided. Therefore most people do not really understand that it
makes a difference when doing 5D or 6D.

4) Ideally one would
a) Do ALL or nothing, meaning dispersion AND chromaticty with 5D
b) In CASE ALL: mark them say with a star: disp1* or disp(5D), DQ1* or DQ1(5D)
and at least in the manual a statement.
c) Alternative one would have a flag (maybe default = true for backwards compatibility)
and it ONLY calculates both when true. I even would like that best!

The trouble is that we have a certain responsibility even in educating the users
to make them understand the importance of the physics involved.

Maybe you have even a better idea and I am willing to think more!

Cheers, FS 

___
#### 2017-01-23 17:58:16: Piotr.Skowronski@cern.ch commented

Dear Frank,

Of course it could be implemented. On the other hand, everyone could run 5D in case dispersion or chroma calculation was crucial.
It is true that it should be marked clearly in the documentation that the 6D dispersion is less precise then 5D.

I will add your request to TRAC.

Cheers,
Piotr

**Comment by tpersson** [comment]
Looking at later threads I think this discussion is outdated so I will close it.
