### ISSUE TITLE
M. Titze's CF formalism in PTC

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#419]
*Issue migrated from trac ticket # 419*

**component:** _build | **priority:** major
___
#### 2017-03-07 18:37:07: frs commented

In MAD-X we cannot follow the extreme rigour of PTC and its author. One of the major exceptions needed for our work is the fact, that we need to keep the thin lens formalism fully extended to agree in the limit of infinite kicks with the thick lattice. I had a decade ago added pseudo quadrupole to the kick that replaces a thick dipole such that the weak dipole focussing is being properly considered. For the CF magnets the same must be done for the pseudo sextupoles. In case we extend the CF to include octupoles we have to that also for PTC.

___
#### 2017-04-10 11:09:44: @ldeniau commented

2017.04.10 from ldeniau

The map to be modified is not used by E. Forest, so we can safely add new feature to this map. The function to modify is in the file
 madX/libs/ptc/src/Sh_def_kind.f90 subroutine KICKTR (line 3175) for now.

Please make a proposal and the code will be added to the repository. Thank you for your help.

**Comment by tpersson** [comment]
This is included in MAD-X as an option
