### ISSUE TITLE
SXFWRITE does not save cavity property frequency

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#421]
*Issue migrated from trac ticket # 421*

**component:** _build | **priority:** major
___
#### 2017-04-07 10:52:39: ttydecks commented

Hi,
when using SXFWRITE to save a sequence, it does not include all parameters specified in the rfcavity command. Amongst others, the left out parameters are f.i. frequency, no_cavity_totalpath.
When loading the sequence later on with SXFREAD, this information is therefore not at hand and subsequent commands like PTC will not detect the cavities as the frequency is missing. 

In the attached example "run.madx", please compare the original sequence with the one saved after running "run.madx" ("CAV.seq") and observe that the frequency is not saved. 

Here is the header of my current MADX version:
  ++++++++++++++++++++++++++++++++++++++++++++
  +     MAD-X 5.02.13  (64 bit, Linux)       +
  + Support: mad@cern.ch, http://cern.ch/mad +
  + Release   date: 2016.12.20               +
  + Execution date: 2017.04.07 10:43:10      +
  ++++++++++++++++++++++++++++++++++++++++++++

Thank you very much for your support,
Tobias Tydecks
___

**Comment by ldeniau** [comment]
Thomas, did you fix it as part of your big PR or is it still a valid issue?

**Comment by tpersson** [comment]
This is fixed in #734
