### ISSUE TITLE
The sigma matrices are not correctly calculated when initial conditions are given and coupling is present.

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#425]
*Issue migrated from trac ticket # 425*

**component:** mod_twiss | **priority:** major
___
#### 2017-06-21 13:11:59: tpersson commented

If you start at one point with coupling already introduced the sigma matrices will still be zero. 

___
#### 2017-06-21 13:21:28: tpersson uploaded file [`twissWandWOinitialConditions.madx`](https://raw.githubusercontent.com/MethodicalAcceleratorDesign/madx-tickets/master/attachments/425/twissWandWOinitialConditions.madx) (1.0 KiB)

Example showing the differences when a beta-block has been saved and then used as initial conditions. Note that the rest of the parameters are correct it is only the sigma matrices that are different.

**Comment by tpersson** [comment]
This issue should be solved now. I have tried it for several optics and it seems to work fine.
