### ISSUE TITLE
Crash of match, use_macro with weight

### ISSUE THREAD

**Issue by piotrskowronski** [MethodicalAcceleratorDesign/MAD-X#442]
The script below crashes madx.

!!!!! start of the script
match,  use_macro;
  m_ir6b2: macro =
   {
     print, text="Next Line will Seg. Fault";
   };
  weight, mux=10, muy=10;
endmatch;
!!!!! end of the script

**Comment by ldeniau** [comment]
This is a bug, but with low priority for now.

**Comment by tpersson** [comment]
#854 fixes the segmation fault and also shows in the documentation how you can specify a weight for a macro.
