### ISSUE TITLE
Twiss displays not zero rotation angle for the entrance pole face when it is zero

### ISSUE THREAD

**Issue by bogomyag** [MethodicalAcceleratorDesign/MAD-X#445]
Hello, 

twiss shows not zero E1 and E2 for RBEND, however in sequence file they are zero.

the test script in zip archive

Anton

  ++++++++++++++++++++++++++++++++++++++++++++
  +     MAD-X 5.03.06  (64 bit, Windows)     +
  + Support: mad@cern.ch, http://cern.ch/mad +
  + Release   date: 2017.05.29               +
  + Execution date: 2017.07.07 14:31:08      +
  ++++++++++++++++++++++++++++++++++++++++++++

show,BC1.1;
parameter: angle   expression: anglebc1  :: value:    0.00276309956578123
double value:    0.00276309956578123
parameter: e1   expression: 0 * anglebc1  :: value:                      0
double value:                      0
parameter: e2   expression: 0 * anglebc1  :: value:                      0
double value:                      0

table( twiss bc1.1 angle ) =    0.00276309956578123 ;
table( twiss bc1.1 e1 ) =    0.00138154978289062 ;
table( twiss bc1.1 e2 ) =    0.00138154978289062 ;

[1.zip](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/1130944/1.zip)

**Comment by tpersson** [comment]
This is due to the fact that internally e1 and e2 are the angles to the reference orbit while the input is the angle of the pole faces. This is done by choice like this for the output. The documentation is updated to clarify this point in #687
