### ISSUE TITLE
ptc_normal does not calculate chromaticities higher than 4th order

### ISSUE THREAD

**Issue by bogomyag** [MethodicalAcceleratorDesign/MAD-X#446]
The last version of mad-x does not calculate chromaticities higher than 4th order, previous did calculate.
The example script in zip archive.

Anton

  ++++++++++++++++++++++++++++++++++++++++++++
  +     MAD-X 5.03.06  (64 bit, Windows)     +
  + Support: mad@cern.ch, http://cern.ch/mad +
  + Release   date: 2017.05.29               +
  + Execution date: 2017.07.07 14:31:08      +
  ++++++++++++++++++++++++++++++++++++++++++++

dq1_0=1.400000e-001                 dq2_0=2.200001e-001
dq1_1=-7.925845e-003                 dq2_1=-2.724326e-002
dq1_2=-2.892676e+001                 dq2_2=-5.777137e+002
dq1_3=-2.464733e+005                 dq2_3=9.969807e+005
dq1_4=2.430646e+007                 dq2_4=-6.011791e+007
dq1_5=-0.000000e+000                 dq2_5=-0.000000e+000
dq1_6=-0.000000e+000                 dq2_6=-0.000000e+000

[2.zip](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/1130950/2.zip)

**Comment by piotrskowronski** [comment]
I confirm the issue with .sub. operator of PTC.
Until I fix it, as a work around please use ptc_twiss command with normal=true:

	ptc_twiss, closed_orbit,normal, icase=5, no=8;
	write, table=nonlin,file=nonlin.tfs;ptc_end;
	dq1_0=table(nonlin,Q1_P,value);
	dq2_0=table(nonlin,Q2_P,value);
	dq1_1=table(nonlin,Q1_P2,value);
	dq2_1=table(nonlin,Q2_P2,value);
	dq1_2=table(nonlin,Q1_P3,value);
	dq2_2=table(nonlin,Q2_P3,value);
	dq1_3=table(nonlin,Q1_P4,value);
	dq2_3=table(nonlin,Q2_P4,value);
	dq1_4=table(nonlin,Q1_P5,value);
	dq2_4=table(nonlin,Q2_P5,value);
	dq1_5=table(nonlin,Q1_P6,value);
	dq2_5=table(nonlin,Q2_P6,value);
	dq1_6=table(nonlin,Q1_P7,value);
	dq2_6=table(nonlin,Q2_P7,value);

**Comment by piotrskowronski** [comment]
Remark concerning ptc_twiss: you need to divide the result by n! to get value identical to ptc_normal 
dq1_0=table(nonlin,Q1_P,value)/2;
dq2_0=table(nonlin,Q2_P,value)/2;
dq1_1=table(nonlin,Q1_P2,value)/6;
dq2_1=table(nonlin,Q2_P2,value)/6;
dq1_2=table(nonlin,Q1_P3,value)/24;
dq2_2=table(nonlin,Q2_P3,value)/24;
dq1_3=table(nonlin,Q1_P4,value)/120;
dq2_3=table(nonlin,Q2_P4,value)/120;
dq1_4=table(nonlin,Q1_P5,value)/720;
dq2_4=table(nonlin,Q2_P5,value)/720;

**Comment by piotrskowronski** [comment]
Fixed in the new PTC.
