### ISSUE TITLE
ptc_normal, ptc_twiss and ptc_track refactoring

### ISSUE THREAD

**Issue by piotrskowronski** [MethodicalAcceleratorDesign/MAD-X#447]
Proposal for refactoring of the commands to deal with

- provide a switch to allow user choose if the provided parameters are partial derivatives or plain coefficients of the Taylor series (GENFU business) in ptc_normal and ptc_twiss.

- proposal for making ptc_normal a wrapper around ptc_twiss. This would ignore entirely ptc_select_normal. In this scenerio ALL the components will be put in the output table instead of only selected ones

- state of PTC (TIME, RADIATION, EXACT_MIS) should be controlled only via ptc_setswitch and the corresponding flags should be removed from all the other commands because it creates a huge mess in the code and confuses the users.

**Comment by ldeniau** [comment]
This refactoring is significant work, and we don't have the resource for such large refactoring.
