### ISSUE TITLE
bug importing errors to PTC (ealign and ptc_read_errors)

### ISSUE THREAD

**Issue by piotrskowronski** [MethodicalAcceleratorDesign/MAD-X#448]
Reported by James Hunt at Cockcroft Co UK.

When a rectangular aperture is translated and rotated in psi (around S axis) the footprint of the surviving particles is clearly wrong. Example was communicated by email to mad.support

**Comment by ldeniau** [comment]
Please attach files to the issue.

**Comment by piotrskowronski** [comment]
Simplified example showing the issue and plot of its result.
It puts quad with rectangular aperture of 10cm.
Quad is misaligned phi=30deg, dx=30cm.

The plot  shows footprint of tracks surviving quad and its shape is clearly wrong, starting from and offset in Y. 

![image](https://user-images.githubusercontent.com/16878140/35328592-273a37ca-00fd-11e8-825b-f5af4a4df021.png)
[test-ptc-twiss-align-srot.madx.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/1659537/test-ptc-twiss-align-srot.madx.txt)

**Comment by piotrskowronski** [comment]
Fixed with pull request #545
