### ISSUE TITLE
Add thick Solenoid in Track

### ISSUE THREAD

**Issue by ldeniau** [MethodicalAcceleratorDesign/MAD-X#473]
The thick map of the solenoid could be added in Track, but first we much check that the thick map is symplectic. This also need to update makethin to leave selected solenoid in thick version.

**Comment by HelmutCERN** [comment]
Makethin part done : adding thick attribute to solenoid in dictionary and implementing thick slicing for solenoids. Example:
select, flag=makethin, class=solenoid, thick=true, slice=5;
After quadrupoles and bends, solenoids are now the third element type for which thick slicing has been implemented, such that makethin becomes more and more a general slicing tool where the result can be thick or thin slices. In consequence, changing internally names and structures in makethin to distinguish between "sliced element" for general slicing and specific cases of thick or thin elements.
Also making an effort to implement solenoid and other magnet slicing as similar as possible by putting common code into separate new internal utilities like "copy_params_from_thick".
