### ISSUE TITLE
ptc_track norm_no parameter

### ISSUE THREAD

**Issue by piotrskowronski** [MethodicalAcceleratorDesign/MAD-X#496]
@orblancog@gmail.com

Dear mad team,

in the madx manual I see two different definitions :
norm=integer in the header of the ptc_track description
norm_no in the description

which one of these is correct ?
does it track a linear lattice when this parameter is not set ?

From some trackings I feel that the default is not one, could you confirm ?

best regards,
o
-- 
Oscar BLANCO

**Comment by piotrskowronski** [comment]
norm_no is the correct one. 
I fixed the manual. 

I also added clarifications to the manual:

The tracking can be done element-by-element or ”turn-by-turn”. In the first case particle
coordinates are tracked from element to element, and if an element is an observation point
them the coordinates are saved in a table. In the second case particle coordinates are always
tracked over full turn (from start to start) and afterwards these coordinates are transfrmed
using Transfer Map from the start to a given observation point. The order of the transfer
map is defined by NORMAL NO switch.

NORM NO: order of the intrenally used Transfer Maps and Normal Forms.
NORM NO=1 makes them linear (always true for MAD-X).
The Transfer Maps are used to transfrom track coordinates from START to
given observation point if ELEMENT BY ELEMENT is false. The Normal Form is
used to transfrom coordinates between cartesian and action-angle variables.

Let me know if you need more clarification.

When looking into the code to answer your question I found that ptc_track with element_by_element=false was actually broken in the current version (seg. fault). Fixed now, but in case 
you have trouble running the code need to wait to a new release.

**Comment by orblancog** [comment]
it is clear, thank you piotr
