### ISSUE TITLE
ESAVE in version 5.03.07

### ISSUE THREAD

**Issue by listoel** [MethodicalAcceleratorDesign/MAD-X#501]
There seems to be an issue with ESAVE in the latest release. The attached minimal example runs fine in version 5.03.06, but in 5.03.07 it results in 
+++ memory access outside program range, fatal +++

[example.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/1471549/example.txt)

**Comment by coldfix** [comment]
Probably another bug due to my changes.. I'll take a look.

**Comment by tpersson** [comment]
Hi, 
Thanks for reporting this. I guess this is linked to the new way how drifts are handled in the 5.03.07. We will have a look hopefully this week. 

best regards
Tobia

**Comment by tpersson** [comment]
Perfect! Thanks Thomas! I was just about to ask you if it could have come from your changes.
