### ISSUE TITLE
RF cavity defined with HARMON and zero LENGTH gets FREQ set to zero

### ISSUE THREAD

**Issue by ldeniau** [MethodicalAcceleratorDesign/MAD-X#516]
[From R. Di Maria]
We have a small issue here. If a cavity, defined with HARMON, has  zero length, the FREQ attribute is not filled with the correct value and stays zero.

Makethin seems part of the problem. Here is an example. When you give a length to the cavity  you get a frequency.

! Links definitions
option, warn,info;
system,"ln -fns /afs/cern.ch/eng/lhc/optics/runII/2017 2017";

REAL CONST l.ACSCA             = 1e-15; ! needed to have the frequency in the twiss table

! Sequence definition
Option, -echo,-warn,-info;
call,file="2017/lhc_as-built.seq";
call, file="2017/opticsfile.19_ctpps2";
beam;

! it works without slicing
call,file="2017/toolkit/slice.madx";

use,sequence=lhcb1;
select,flag=twiss,pattern="^ACSC.*",column=name,harmon,freq,l;
twiss; write,table=twiss;

**Comment by tpersson** [comment]
Fixed in #858. The RF-cavities were never added to the special RF-Cavity list that updates the frequency.
