### ISSUE TITLE
Support for K0l ~= Angle.

### ISSUE THREAD

**Issue by ldeniau** [MethodicalAcceleratorDesign/MAD-X#517]
We are having a compelling and urgent use case (high energy LHC studies) for dipoles with k0l different from angle.

Physics should take into account the difference between k0l and angle for sbend, rbend and multipoles. The physics is already implemented with field errors, therefore we should interpret k0l-angle as an additional dipolar field error. We cannot use field errors directly because the use statement will wipe out the definitions. 

The logic to preserve backward compatibility could be: for sbend and rbend if `k0` is not specified k0=angle/l, for multipoles if angle is not specified angle=kn0l. Then in twiss and track (k0l-angle) is always added to the dipolar field error components. For instance in tmbend in twiss

dh = (- h * deltap + bvk * f_errors(0) / el) / (one + deltap)

should become

dh = (- h * deltap + bvk * (f_errors(0)+k0l-angle) / el) / (one + deltap)

or in tmmult

dbr = f_errors(0) / (one + deltap)

should become

dbr = (f_errors(0) +normal(0)-angle) / (one + deltap)

What do you think? In case it would be possible to implement this for the next feature release?

Many thanks in advance,
Riccardo

**Comment by HelmutCERN** [comment]
Done in makethin. Writing angle to multipole if different from k0*l.

**Comment by coldfix** [comment]
Hi, does this mean it will not be implemented in normal mode without makethin? If so, can I create a PR for the change as requested above or is there a specific reason not do it?

**Comment by ldeniau** [comment]
What do you mean? The statement concerns spend->angle to multipole->angle. Only makethin is doing this...

**Comment by coldfix** [comment]
Yes, I was asking precisely because the reason given for closing was related to only makethin, while the original issue and my interest concerns thick elements.

If this k0l != angle is handled with makethin but not otherwise, there is an inconsistency right?

**Comment by ldeniau** [comment]
Hi Thomas,

> On 1 Mar 2018, at 14:33, Thomas G. <notifications@github.com> wrote:
> 
> Yes, I was asking precisely because the reason given for closing was related to only makethin, while the original issue and my interest concerns thick elements.
> 
> If this k0l != angle is handled with makethin but not otherwise, there is an inconsistency right?
> 

It is handled specifically in Survey, Track, Twiss, and Emit. See my different PRs on this topic.

Best,
Laurent.
