### ISSUE TITLE
Not possible to use the MVAR 

### ISSUE THREAD

**Issue by tpersson** [MethodicalAcceleratorDesign/MAD-X#543]
It is written in the documentation that it is possible to define your own variable and then use it to match. However, when I check this was only possible in version of MAD-X before V3 which was around 2006. The macro in MAD-X provides a more powerful matching possibility than the MVAR so I would recommend to remove simply remove it from the documentation.

**Comment by 1ronmoore1** [comment]
Actually, it had been functional in v5.02.13.  When I tried v5.03.07 I discovered it was no longer supported.

**Comment by tpersson** [comment]
You are correct. It worked actually all the way up to 5.03.06 as long as the slow flag was used. In my tests I forgot to use it and then we really have to go back long time before it works.
________________________________

**Comment by coldfix** [comment]
Hi, this is due to my patch then. Can you give a minimal example?

**Comment by 1ronmoore1** [comment]
I do not have a minimal example handy, and I won't have time to create one until next week.

For what it's worth, in 5.03.07 I see:

+=+=+= fatal:  +-+-+- fatal error
match - collect: illegal name
      - try with the "slow" option
      - name =  mvar3

whenever I use a constraint with a user variable.  I am using the SLOW flag in my match command.  Despite the fatal error message, the match fit continues, and I now realize that I do get the same numerical results in 5.02.13 and 5.03.07.

**Comment by tpersson** [comment]
That is interesting because in my example I really do get the MAD-X exits and I don't get any matching. I have found the commit that breaks it but there has been many changes around there since then so it is not just to revert that commit. I will try to find a solution for this.

cheers
Tobias
________________________________
