### ISSUE TITLE
Not possible to access orbit_-cT variable from ptc_twiss_summary via table command

### ISSUE THREAD

**Issue by ttydecks** [MethodicalAcceleratorDesign/MAD-X#544]
Hi,
apparently due to its name including a minus, the variable orbit_-cT is not accessible using the standard way via table:
value, table(ptc_twiss_summary, orbit_-cT);
Quotes around the variable do not help. 

Thanks

**Comment by piotrskowronski** [comment]
Changed the name to orbit_T in pull request #548
