### ISSUE TITLE
C++11 features in mad_mkthin.cpp while Makefile uses C++98

### ISSUE THREAD

**Issue by piotrskowronski** [MethodicalAcceleratorDesign/MAD-X#561]
Compilation with Intel 18.1 breaks on multiple lines of mad_mkthin.cpp
src/mad_mkthin.cpp(799): error: identifier "nullptr" is undefined
    if (kn_param == nullptr) return nullptr;

nullptr is a C++11 feature, when I run 
make SHOW=yes  madx-linux64-intel

I see  c++98

icc -m64 -O3 -std=c++98 -Wall -Wcheck -Wp64 -c -diag-disable 2259,1572,981 -mp1 -fp-model strict -D_STATIC -D_ICC -D_ICC -D_IFORT -D_LINUX -D_ONLINE -D_USEGC -DSTATIC=static -Ilibs/gc/gc-7.2f/include src/mad_mkthin.cpp -o build/Linux64_ifort/mad_mkthin.o

**Comment by ldeniau** [comment]
Updated by the last PR.

On 12 Feb 2018, at 11:50, piotrskowronski <notifications@github.com<mailto:notifications@github.com>> wrote:


Compilation with Intel 18.1 breaks on multiple lines of mad_mkthin.cpp
src/mad_mkthin.cpp(799): error: identifier "nullptr" is undefined
if (kn_param == nullptr) return nullptr;

nullptr is a C++11 feature, when I run
make SHOW=yes madx-linux64-gnu

I see c++98

icc -m64 -O3 -std=c++98 -Wall -Wcheck -Wp64 -c -diag-disable 2259,1572,981 -mp1 -fp-model strict -D_STATIC -D_ICC -D_ICC -D_IFORT -D_LINUX -D_ONLINE -D_USEGC -DSTATIC=static -Ilibs/gc/gc-7.2f/include src/mad_mkthin.cpp -o build/Linux64_ifort/mad_mkthin.o

**Comment by ldeniau** [comment]
can we close this issue?
