### ISSUE TITLE
"save" flattens structered sequences removing dependencies

### ISSUE THREAD

**Issue by bogomyag** [MethodicalAcceleratorDesign/MAD-X#578]
Hello,
I have a structured sequence, i.e. sequence that contains two other sequences. I match and change the length of the drifts and lengths of the sequences. As an intermediate step I try to save the variables

set,format="28.15g";
select, flag=save, clear;
select, flag=save, pattern="^KQ";
select, flag=save, pattern="^DD[0-9]";
select, flag=save, pattern="^TB";
save,file="tmp-ir-1.str";

and receive a message

++++++ warning: SAVE makes all previous USE invalid !
++++++ warning: structured sequence flattened: l1_ff

Now I am not able to match the sequence because dependencies are removed.

Is it possible to have "SAVE" not to flatten the sequence?

I use this MAD-X
  ++++++++++++++++++++++++++++++++++++++++++++
  +     MAD-X 5.03.07  (64 bit, Windows)     +
  + Support: mad@cern.ch, http://cern.ch/mad +
  + Release   date: 2017.10.20               +
  + Execution date: 2018.02.21 11:30:28      +
  ++++++++++++++++++++++++++++++++++++++++++++

**Comment by tpersson** [comment]
There is no way to save the dependencies and I think only if there would be a very strong use case this would be reviewed since it is would need a lot of modifications to the code.
