### ISSUE TITLE
lrad not saved for collimator, comments not as expected in twiss output

### ISSUE THREAD

**Issue by HelmutCERN** [MethodicalAcceleratorDesign/MAD-X#619]
In the example shown below, the existing attribute lrad, visible with show and in twiss output, is not written when the sequence is saved. For other simple elements, like placeholder, lrad is saved.

A nice new feature is that comments can now be defined and get saved, but seem to become "0" in twiss output.

co  : collimator,    lrad=1.,comments="Thick:=1,Material=Cu";
pl  : placeholder,   lrad=1.;

testseq: sequence,l=2;
  co, at=pos;  pos=0.5;
  pl, at=pos;  pos=1.5;
endsequence;

beam;

show,co; // lrad is there

use,sequence=testseq;

select, flag=twiss, column=name,keyword,s,lrad,comments;
twiss, sequence=testseq, file="testseq_twiss.tfs", betx=1.,bety=1.;

save,sequence=testseq,file="testseq.seq";

**Comment by tpersson** [comment]
I forgot the lrda part of the question. Also there is a question if it would be possible to not have it in capital letters.

**Comment by tpersson** [comment]
This is fixed in PR #633
