### ISSUE TITLE
Round of in fort.2 to SixTrack

### ISSUE THREAD

**Issue by vkbo** [MethodicalAcceleratorDesign/MAD-X#620]
The precision of the generated fort.2 file for SixTrack appears to be too low.
A tolerance on the sum of lengths has been added to SixTrack, which is set to 1 µm. The sum is currently off by slightly more than that margin. The fort.2 output precision is 1e-9, which may be the reason for this. Would it be possible to increase the precision of the output?

**Comment by madcern** [comment]
This is fixed in PR #631
