### ISSUE TITLE
PTC crash when built on Ubuntu 17.10, gcc  7.2.0

### ISSUE THREAD

**Issue by tpersson** [MethodicalAcceleratorDesign/MAD-X#623]
PTC crashes when running the following examples:
test-aperture-2
test-ptc-twiss-2
test-ptc-twiss-old5.out

It seems to be some memory leak (from top):
3810 mad       20   0 3891916 3.516g   1124 R  95.8 91.4   0:17.52 madx64 

The process ends with:
Killed

**Comment by tpersson** [comment]
This problem does not occur on Ubuntu 18.04 and gcc 7.3.0. I think the best solution to this is to upgrade the virtual machine.

**Comment by piotrskowronski** [comment]
I believe it is confirmed to be the OS problem, not ours. Can we close the issue?

**Comment by tpersson** [comment]
I agree
