### ISSUE TITLE
Matching with ptc_normal

### ISSUE THREAD

**Issue by bogomyag** [MethodicalAcceleratorDesign/MAD-X#637]
I use ptc_normal in matching routine and once in a while I receive an error and madx stops.

>At line 177 of file src/madx_ptc_normal.f90
>Fortran runtime error: End of record

In the matching I calculate tunes at different delta p, close to the end of bandwidth. It could be that optics is not stable at given delta p. It would have been better instead of error and termination of the program to have a warning.

Here is a sample of using ptc_normal in matching macro
select_ptc_normal, q1=0, q2=0;
ptc_normal,closed_orbit,normal,icase=5,no=1,deltap= dpp;
q1_0=table(normal_results,value,1);
q2_0=table(normal_results,value,2);

Here is the version of madx

  ++++++++++++++++++++++++++++++++++++++++++++
  +     MAD-X 5.04.00  (64 bit, Windows)     +
  + Support: mad@cern.ch, http://cern.ch/mad +
  + Release   date: 2018.03.02               +
  + Execution date: 2018.06.14 18:15:27      +
  ++++++++++++++++++++++++++++++++++++++++++++

**Comment by piotrskowronski** [comment]
Hi,

You are perfectly right. 
It is unwanted behaviour of updated PTC and I will try to fix it.

Piotr

**Comment by piotrskowronski** [comment]
Please, could you send me you full script so I can check where it stops in your case?

**Comment by tpersson** [comment]
@bogomyag . Could we close this issue or do you still expereince this problem? In case you do could you provide us with the example?

**Comment by bogomyag** [comment]
I can give you an example, but the errors appears after about 12 hours of work on AMD Ryzen 9 3950X . I mean that I launch matching routine and after this time it ends with an error message. It is optimization of tau-charm factory dynamic aperture. If you are willing to investigate I can send the lattice and the scripts.

**Comment by tpersson** [comment]
I think that will be very hard/time consuming to debug such a complicated study. We normally ask for a "as simple as possible" script that is showing the problem. Is there any way you can reproduce the problem with a shorter script? Many thanks in advance.

**Comment by bogomyag** [comment]
I can't provide a simple script.

**Comment by ldeniau** [comment]
Sorry, but we cannot spend resources on 12h scripts to debug the problem on this specific architecture.
