### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by dhruvd2** [MethodicalAcceleratorDesign/MAD-X#638]
Hello,
I am a relative newcomer to Madx and tried to access Madx today using command prompt. An error message saying 
A s s e r t i o n   f a i l e d !

 P r o g r a m :   C : \ U s e r s \ D h r u v   D e s a i \ D e s k t o p \ M a d x \ m a d x - w i n 6 4 - g n u . e x e
 F i l e :   s r c / m a d _ m a c . h ,   L i n e   2 2

 E x p r e s s i o n :   d s t   & &   s r c   & &   s i z   <   I N T _ M A X

was displayed, and the program crashed immediately after that. Although I have run Madx successfully a couple of days back, the same program gives me an error while running today.

**Comment by tpersson** [comment]
Hi, 
This error is coming form the garbage collector used in MAD-X, when running on  Windows 10 after the April update. We are currently working to find a solution to the problem but at the moment the work around would be to revert the windows version to a version before that patch (1803).

**Comment by ldeniau** [comment]
duplicate with #616
