### ISSUE TITLE
How to do calculations while tracking the beam

### ISSUE THREAD

**Issue by dhruvd2** [MethodicalAcceleratorDesign/MAD-X#639]
Hello,
I am a newcomer to MAD-X . Currently I am writing a simple program to simulate beam dynamics through a storage ring consisting of multiple FODO cells and all linear elements.  I am tracking 1000 particles for 1024 turns. The snippet for that is as follows(Assume all other elements are defined):

MAKETHIN, SEQUENCE=FODO;

USE, SEQUENCE=FODO;

TRACK, FILE=basis, DUMP, ONETABLE;

NSTEP:=1000;

SX:=0.0011633;

SY:=0.00073129;

step:=0;

X_SUM:=0;

WHILE(step<NSTEP){

XS:=SX*GAUSS();

YS:=SY*GAUSS();

PTS:=0;

PXS:=0;

PYS:=0;

TS:=0;

X_SUM=X_SUM+XS;

START, X=XS, Y=YS, T=TS;
step=step+1;

}

RUN,TURNS=1024;

ENDTRACK;

I want to compute the centroid for 1000 particles at every turn, so that I can track the centroid as a function of the number of turns. Is there anyway I could insert information within this code snippet that lets me compute the centroid for each turn?

**Comment by ldeniau** [comment]
question on MAD-X should be addressed to mad@cern.ch, not to the issue system.

**Comment by ldeniau** [comment]
please ask your question on mad@cern.ch such that we can reply to your email address.

**Comment by ldeniau** [comment]
As mentioned on the web site, please provide a simple self-content example that we can run.
