### ISSUE TITLE
Incrementing loop variable generates messages about redefinition

### ISSUE THREAD

**Issue by Dominik1123** [MethodicalAcceleratorDesign/MAD-X#644]
In the [MADX user's guide](http://madx.web.cern.ch/madx/releases/last-rel/madxuguide.pdf#section.3.2) the following example for using `while` loops is given:

	n = 1; m = 1;

	while (n <= 10) {
	    m = m * n;
	    value, m;
	    n = n + 1;
	}

This example code generates lots of messages about redefinition of `m` and `n` (to be precise one per variable and iteration). For longer loops (building long sequences) this really clutters the output. Is there a way to increment loop variables without generating these kind of messages? I tried `n += 1;` but this failed with the warning `++++++ warning: statement not recognised: n`.

**Comment by ldeniau** [comment]
Dear Dominik,

The normal way to ask questions on MAD-X is to send emails to mad@cern.ch<mailto:mad@cern.ch>. Issues are about code developments (bugs, new features, etc…).

On 4 Jul 2018, at 15:57, Dominik1123 <notifications@github.com<mailto:notifications@github.com>> wrote:


In the MADX user's guide<http://madx.web.cern.ch/madx/releases/last-rel/madxuguide.pdf#section.3.2> the following example for using while loops is given:

n = 1; m = 1;

while (n <= 10) {
    m = m * n;
    value, m;
    n = n + 1;
}


This example code generates lots of messages about redefinition of m and n (to be precise one per variable and iteration). For longer loops (building long sequences) this really clutters the output. Is there a way to increment loop variables without generating these kind of messages? I tried n += 1; but this failed with the warning ++++++ warning: statement not recognised: n.


You have to set

option -info;

to disable such messages.

Best,
Laurent

--
Laurent Deniau                           http://cern.ch/mad
Accelerators Beam Physics        mad@cern.ch<mailto:mad@cern.ch>
CERN, CH-1211 Geneva 23       Tel: +41 (0) 22 767 4647

**Comment by Dominik1123** [comment]
Hi Laurent,

thanks for the hint, but actually I don't want to disable all info statements, I'd like to keep the useful ones. However for incrementing a loop variable this type of information is rather redundant. Since I didn't find a "clean" way to do this job, I considered it a possible feature requirement.
I suppose that using loops for building sequences is a common thing and since MADX intrinsically supports loops it feels a bit odd that there is no "clean" way of incrementing loop variables.
The `+=` syntax appears very natural in that sense.

On the other hand, as a user, I can also filter that stuff myself (`grep -vE "^\+{6} info: [mn] redefined"`) so it's probably not worth the effort implementing this.
Anyway thanks for the suggestion!

Best wishes,
Dominik
