### ISSUE TITLE
Makethin does not convert bends correctly when k0=0

### ISSUE THREAD

**Issue by tpersson** [MethodicalAcceleratorDesign/MAD-X#664]
It seems that after the update of having k0 for bending magnets the angle is not converted when angle is used and k0=0. This happens apparently in some scripts. The issue was seen in a study from @JacquelineKeintzel (think it was HELHC).
Bellow is my minimal example showing the issue (wang is fine but wang_k0 is not):
 
wang: SBEND, l=1.0, angle=0.05;
wang_k0: SBEND, l=1.0, angle=0.05, k0=0;
woutang: SBEND, l=1.0, angle=0.0, k0=0.1;
withboth: SBEND, l=1.0, angle=0.15, k0=0.20;
seq: sequence, refer=center, l=4;
wang, at=1;
wang_k0, at=2;
woutang, at=3;
withboth, at =4;

endsequence;
SELECT, FLAG=makethin,slice=1;
makethin, sequence=seq, MAKEDIPEDGE=false;
save,sequence=seq,file="thin.seq";

**Comment by HelmutCERN** [comment]
Fixed in create_sliced_magnet by removing fabs(k0val)>0 check

**Comment by tpersson** [comment]
I tried this change but now some of the tests (e.g. test-dynap) don't pass anymore.  Could you have a look?

**Comment by tpersson** [comment]
I added this line and now the simple test works fine. There are still two tests that are broken due to this but it is only numerical . Before a constant was defined as k=a/l and then k0 = a*l now it is k0=a. This gives small numerical differences to break 2 tests. If @HelmutCERN agrees with this solution than I will update the test and make a PR. 
if(fabs(k0val) < eps)
      { //This is in case k0 is defined but 0
        kn_pars[0]=k0_from_angle(angle_param); // k0 generated from angle
        mult_with_length = false; // angle is already  k0 * length
      }

**Comment by HelmutCERN** [comment]
Dear Tobias,

probably fine, but I would also like to run some tests myself.
I am in the LMC which will still take a while.

Can I see whole section of   SeqElList::create_sliced_magnet    (on some branch or publically accessible place ?)
to try to run with the same algorithm as you ?

See you then later, after the meeting or tomorrow.

Cheers, Helmut

**Comment by HelmutCERN** [comment]
Dear Tobias,

I ran quick checks, looks good, always generated knl as expected and in addition angle when containing different information.

Cheers, Helmut

**Comment by tpersson** [comment]
#666 closes this issue.
