### ISSUE TITLE
Building problems with CMake version 2.8

### ISSUE THREAD

**Issue by peremato** [MethodicalAcceleratorDesign/MAD-X#669]
In the context of the LCG releases I am having a problem building mad-x on slc6 with gcc 6.2 and CMake version 2.8. Using CMake version 3.11 it builds successfully. 

The actual error is 
```
/build/sftnight/GeantV/build/externals/madx-5.04.01/src/madx/5.04.01/src/mad_mkthin.cpp: In function ‘void place_thin_slice(const node*, sequence*, element*, double)’:
/build/sftnight/GeantV/build/externals/madx-5.04.01/src/madx/5.04.01/src/mad_mkthin.cpp:1132:25: error: ‘nullptr’ was not declared in this scope
     expression* at_expr=nullptr
                         ^~~~~~~
```  
The reason for this compilation error is  that the C++ standard is not set to  c++11 or later, but the it is set to c++98. This is done in the file 
```
cmake/compilers/setupGNU.cmake:    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++98")
``` 
With CMake 3.11 it appends in the compilation flags the option `-std=gnu++11` automatically, therefore fixing the problem.

**Comment by coldfix** [comment]
Hi, this should be fixed in 59d136a7872a1ca04c4a3ad5676559b4ae1f095a and will be part of the next release.

**Comment by peremato** [comment]
Thanks!

**Comment by tpersson** [comment]
I think this works with the latests release. Correct?
