### ISSUE TITLE
Inconsistent handling of semi-defined apertures between APERTURE module and SIXTRACK converter

### ISSUE THREAD

**Issue by roman-martin** [MethodicalAcceleratorDesign/MAD-X#693]
!----EXAMPLE-----------------------------------------------------------------------

!---One element has explicitely defined apertype but no actual apertures
TDI1: MARKER;
TDI2: MARKER, APERTYPE="circle";

testseq: SEQUENCE, l = 20.0;
		  TDI1, at=10;
        TDI2, at=15;
ENDSEQUENCE;

!---the usual stuff
BEAM, PARTICLE=PROTON, ENERGY=7000.0, EXN=2.2e-6, EYN=2.2e-6;
SELECT,FLAG=TWISS,CLEAR;
SELECT,FLAG=TWISS,COLUMN=NAME,KEYWORD,S,L,APERTYPE,APER_1,APER_2,APER_3,APER_4;
USE, SEQUENCE=testseq;

!---produce APERTURE and SIXTRACK output: APERTURE shows no apertures, SIXTRACK has an aperture
TWISS, BETX=100, BETY=100, file=twiss.out;
APERTURE, file=aperture.out;
sixtrack, APERTURE, MARKALL;

!---Compare the two elements as seen by user
show, tdi1;
show, tdi2;

!---/EXAMPLE-----------------------------------------------------------------------

The example produces 2 elements, one without apertype, on with explicitely defined apertype. In the following APERTURE calculation, neither element is an obstacle, the n1 values are as if no apertures exists. Both have a "Circle" apertype though, even if only one had it defined before.
In the Sixtrack fc.2 file however, the element with explicitely defined apertype now has an aperture of zero. Within MAD-X we have no way of seeing the difference as can be seen by the "show" output.

**Comment by roman-martin** [comment]
The main issue here is that this behaviour can be triggered without doing anything shady as shown in #694, and that there is a difference between what MAD-X calculates and what it converts to Sixtrack.

Workarounds are not defining APERTYPE without also giving aperture values, as well as not installing previosly undefined elements with seqedit.

**Comment by tpersson** [comment]
This is fixed in #736 (which also explains how it deals with it)
