### ISSUE TITLE
Installing previously undefined elements via seqedit can trigger issue #693

### ISSUE THREAD

**Issue by roman-martin** [MethodicalAcceleratorDesign/MAD-X#694]
!----EXAMPLE-----------------------------------------------------------------------

!---Predefine a marker
TDI1: MARKER;

testseq: SEQUENCE, l = 20.0;
	TDI1, at=5;
ENDSEQUENCE;

!---install new elements in existing sequence
seqedit, sequence=testseq;
	install, element=TDI2, class=marker, at=15;
endedit;

!---Saving result writes all possible attributes into the output file
save, sequence=testseq, file="myseq.seq";

!----EXAMPLE-----------------------------------------------------------------------

If I install a new element using the "class" parameter of seqedit's install command, then SAVE will write every possible attribute into the output file. This includes the default apertype "Circle" and the default radius 0. If the saved sequence is loaded and converted to Sixtrack output the "defined" zero radius triggers issue #693 and the resulting sixtrack files will have a zero aperture element and it is not possible to see this in MAD-X.

It is possible to avoid this issue by defining the element beforehand, instead of using the "class" parameter.

**Comment by tpersson** [comment]
This is fixed in #736 (which also explains how it deals with it)
