### ISSUE TITLE
Saving variables to file via select, flag=save produces empty file

### ISSUE THREAD

**Issue by JoschD** [MethodicalAcceleratorDesign/MAD-X#696]
As stated in the user's guide under 4.11 it should be possible to save variables to an output file via:

abc = 10;
SELECT, FLAG=SAVE, CLASS=variable, PATTERN="abc.*";
SAVE, FILE=mysave;

running the code above results in an empty "mysave" file, though.
(Tested in Version 5.04.02 64bit Linux)

**Comment by tpersson** [comment]
The problem seems to be when the class=variable is used. The pattern selection seem to work.
________________________________
