### ISSUE TITLE
rfcavity doesn't take charge into account

### ISSUE THREAD

**Issue by coldfix** [MethodicalAcceleratorDesign/MAD-X#701]
Hi,

Stefan Sorge from GSI mentioned to me that he was surprised to discover that the particle charge is not taken into account by the RFCAVITY element (`ttrf()` in `trrun.f90`).

Is this as intended or should charge be considered here (probably only its absolute value)? If not, maybe it should be added in the documentation, that one has to scale the `VOLT` parameter for that purpose instead.

Best, Thomas

**Comment by tpersson** [comment]
Manual update in #858
