### ISSUE TITLE
Inconsistency in trphot() of trrun.f90

### ISSUE THREAD

**Issue by alatina** [MethodicalAcceleratorDesign/MAD-X#704]
Line 4740 invalides any input value passed to trphot() as parameter deltap

Solution to be implemented: commenting out that line, and correctly initializing the variable 'deltap' starting from 'pt' which is what is normally passed to trphot() in the whole TRACK module.

**Comment by tpersson** [comment]
This should be fixed with the PR #697, correct?

**Comment by alatina** [comment]
Hum, not really. The two things are unrelated. Yet, i see that the current version of trrun.f90 have the right code....

**Comment by tpersson** [comment]
Yes, it is in the master. That commit you reference  was included in the PR #697 (even though I agree that they are not related)
