### ISSUE TITLE
unexpected warnings from survey

### ISSUE THREAD

**Issue by ldeniau** [MethodicalAcceleratorDesign/MAD-X#707]
the attached script emits the following unexpected warnings (more related to twiss).
[survey_bend.madx.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/2671936/survey_bend.madx.txt)

 TWDISP: Unable to compute intial dispersion --- dispersion set to zero.
 TWDISP: Unable to compute intial dispersion --- dispersion set to zero.
++++++ warning: double_from_table_row: column not found: survey->k1l
++++++ warning: double_from_table_row: column not found: survey->k1sl
++++++ warning: double_from_table_row: column not found: survey->k2l
++++++ warning: double_from_table_row: column not found: survey->k2sl
++++++ warning: double_from_table_row: column not found: survey->k3l
++++++ warning: double_from_table_row: column not found: survey->k3sl
++++++ warning: double_from_table_row: column not found: survey->k1l
++++++ warning: double_from_table_row: column not found: survey->k1sl
++++++ warning: double_from_table_row: column not found: survey->k2l
++++++ warning: double_from_table_row: column not found: survey->k2sl
++++++ warning: double_from_table_row: column not found: survey->k3l
++++++ warning: double_from_table_row: column not found: survey->k3sl
++++++ warning: double_from_table_row: column not found: survey->k1l
++++++ warning: double_from_table_row: column not found: survey->k1sl
++++++ warning: double_from_table_row: column not found: survey->k2l
++++++ warning: double_from_table_row: column not found: survey->k2sl
++++++ warning: double_from_table_row: column not found: survey->k3l
++++++ warning: double_from_table_row: column not found: survey->k3sl
++++++ warning: double_from_table_row: column not found: survey->k1l
++++++ warning: double_from_table_row: column not found: survey->k1sl
++++++ warning: double_from_table_row: column not found: survey->k2l
++++++ warning: double_from_table_row: column not found: survey->k2sl
++++++ warning: double_from_table_row: column not found: survey->k3l
++++++ warning: double_from_table_row: column not found: survey->k3sl
++++++ warning: double_from_table_row: column not found: survey->k1l
++++++ warning: double_from_table_row: column not found: survey->k1sl
++++++ warning: double_from_table_row: column not found: survey->k2l
++++++ warning: double_from_table_row: column not found: survey->k2sl
++++++ warning: double_from_table_row: column not found: survey->k3l
++++++ warning: double_from_table_row: column not found: survey->k3sl

**Comment by coldfix** [comment]
Probably the same issue as described in  #490: plot should be patched to check if the table contains the given columns at all and skip this part if it doesnt.

**Comment by ldeniau** [comment]
I confirm that the problem is the same as for #490, but my guess is different.

It looks like that PLOT expects a TWISS table when haxis=s (i.e. TWDISP message) and tries to plot the lattice layout on the top, that is why it looks for the magnets strengths in the table to draw them above or below the line (i.e. focusing/defocusing quadrupoles, sextupoles, octupoles and skews).

I am not sure that we can fix it, unless we trust the table header TYPE and disable the top layout (and the reading the DISP) when the type is not TWISS... Is it useful to have the layout on the top for non-TWISS plots? Aperture?

**Comment by ldeniau** [comment]
ugly fix, disabling warnings as the logic of this module is quite complicated...
