### ISSUE TITLE
MKTHIN of RBEND disregards E1 and E2

### ISSUE THREAD

**Issue by alatina** [MethodicalAcceleratorDesign/MAD-X#710]
When an RBEND passes through MKTHIN, becomes an SBEND with

E1 = ANGLE / 2;
E2 = ANGLE / 2;

which is fine.

But if the user provides the entrance and exit angles, E1 and E2, instead of an SBEND with

E1 = E1 + ANGLE/2;
E2 = E2 + ANGLE/2;

one gets:

E1 = ( ( 0 ) + ANGLE/2);
E2 = ( ( 0 ) + ANGLE/2);

That is, the inputs E1 and E2 are lost

**Comment by alatina** [comment]
option, -debug, -echo;

lmb = 10.;
amb = 0.010;
mb1: rbend, l=lmb, angle=amb, e1 = 1, e2 = 2;

myseq: sequence, l=11, refer=centre;
mb1, at:= 5.5;
endsequence;

beam,energy=1.e6;
use, sequence=myseq;

select, flag=makethin, class=rbend, thick=true;

makethin, sequence=myseq, style=teapot, makedipedge=false;
use, sequence=myseq;

save, sequence=myseq, file="thin.seq";

**Comment by alatina** [comment]
Produces the output:

mb1: sbend,l:=( 10 ) * ( 1.0 / sinc ( 0.01 * 0.5 ) ) ,angle:= 0.01,e1:=( 0 ) + ( ( 0.01 ) * ( 0.5 ) ) ,e2:=( 0 ) + ( ( 0.01 ) * ( 0.5 ) ) ,thick=true;
myseq: sequence, l = 11;
mb1, at = ( 5.5 ) + ( ( ( 10 ) * ( 1.0 / sinc ( 0.01 * 0.5 ) ) ) * ( 0 ) ) ;
endsequence;

**Comment by tpersson** [comment]
#717 is now in master
