### ISSUE TITLE
Issue with TRACK calling TWISS

### ISSUE THREAD

**Issue by alatina** [MethodicalAcceleratorDesign/MAD-X#712]
Tricky bug to descrive. If you run the test test-thick-rbend.madx with option, info; you get different messages  if you run on Mac or Linux:

Linux:

  ++++++++++++++++++++++++++++++++++++++++++++
  +     MAD-X 5.04.02  (64 bit, Linux)       +
  + Support: mad@cern.ch, http://cern.ch/mad +
  + Release   date: 2018.10.03               +
  + Execution date: 2018.12.20 11:46:12      +
  ++++++++++++++++++++++++++++++++++++++++++++
option, -debug, -echo;

enter TRACK module
one pass is on
 TWDISP: Unable to compute intial dispersion --- dispersion set to zero.
 TWDISP: Unable to compute intial dispersion --- dispersion set to zero.

++++++ table: tracksumm

Mac:

  ++++++++++++++++++++++++++++++++++++++++++++
  +     MAD-X 5.04.02  (64 bit, Darwin)      +
  + Support: mad@cern.ch, http://cern.ch/mad +
  + Release   date: 2018.10.03               +
  + Execution date: 2018.12.20 12:36:27      +
  ++++++++++++++++++++++++++++++++++++++++++++
option, -debug, -echo;

enter TRACK module
one pass is on

++++++ table: tracksumm

It all boils down to the following lines in rwiss.f90 starting from line 1588

  call solver(a,4,1,irank)
  
  if (irank.ge.4) then
     DISP(1:4) = A(1:4,5)
  else
     if (get_option('info ') .ne. 0) then
       print *, 'TWDISP: Unable to compute intial dispersion --- dispersion set to zero.'
     endif
     DISP(1:4) = zero
  endif

I found out that on Mac irank = 4, on Linux irank = 0.

**Comment by tpersson** [comment]
On the mac server it only seems to happen for the Intel compiler. It looks like all platform and compiler behaves the same except mac with gnu compiler..

**Comment by ldeniau** [comment]
Check that now it works... Probably a problem with some GCC installation on Mac.
