### ISSUE TITLE
Multipole: length ignored silently

### ISSUE THREAD

**Issue by Number042** [MethodicalAcceleratorDesign/MAD-X#723]
Length for a MULTIPOLE is ignored silently. Drifts are inserted instead, no warning issued. Encountered the issue when translating a lattice from SAD to MAD-X.

**Comment by tpersson** [comment]
Thanks for the discussion and reporting this! I agree that this is not a very nice behavior but to be discussed what is the best plan since there is a chance that people are using this feature (both correctly and wrongly)

**Comment by tpersson** [comment]
A warning has been added in #733
