### ISSUE TITLE
DeltaE/E in the manual

### ISSUE THREAD

**Issue by rdemaria** [MethodicalAcceleratorDesign/MAD-X#726]
I read in the PTC_TWISS section:

"PTC_TWISS can also compute the deltap/p (or deltaE/E if time=TRUE) dependency of theTwiss parameters."

It is also repeated other times.

Are you sure deltaE/E is not deltaE/P_0c=(E-E_0)/P_0c instead? Also are you sure deltap/p is not  deltaP/P_0=(P-P_0)/P_0?

**Comment by ldeniau** [comment]
you are correct, the MAD-X manual should be fixed according to §K.4 and eq. 36 of the PTC manual. Probably some old typos...

**Comment by piotrskowronski** [comment]
Done. Pull request #777.
