### ISSUE TITLE
Aperture ignored in twiss, ok when reading back saved sequence

### ISSUE THREAD

**Issue by HelmutCERN** [MethodicalAcceleratorDesign/MAD-X#731]
Defining first an element without aperture.
Then defining the aperture.
Ignored by twiss.
OK when saving and reading back the sequence.

See sample TestAper attached.

[TestAper.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/2868991/TestAper.txt)

**Comment by tpersson** [comment]
The aperture is changed after the sequence has been built. If the line 
mb, apertype=ellipse, aperture:={ 1,2 };
is moved above the sequence then it works. I agree that it is strange since it is allowed when you re-define elements in that way with different attributes (like k1). I will have a look

**Comment by tpersson** [comment]
I had a quick look again and I think the behavior is actually is correct. It behaves the same for all attributes, it is not linked to the aperture. If we look at the interesting part of the code:

mb: sbend,l:=lenseq;
TestOrder : sequence, l=lenseq;
  mb1: mb, at=lenseq/2;
endsequence; 
We than change mb (NOT mb1):
mb, apertype=ellipse, aperture:={ 1,2 };

This does not trigger a recursive re-defining of the mb1, however, I don't think it should and changing this would break backwards compatibility. If you re-define mb1 on the other hand it all works fine.

**Comment by tpersson** [comment]
I discussed with Helmut and we concluded that it is not a bug, but that it would be nice to have the feature to update all the "chidren" from a parent.

**Comment by madcern** [comment]
This is implemented in PR #733
