### ISSUE TITLE
RFcavity must be sliced for tracking

### ISSUE THREAD

**Issue by ldeniau** [MethodicalAcceleratorDesign/MAD-X#732]
Actually the map of rfcavity for tracking assumes that surrounding drifts are handled by the slicing (i.e. makethin) and implicit drifts. The manual should be updated to mention it.

**Comment by ldeniau** [comment]
Another thing that should be mentioned in the manual is that the number of slices is ignored by make thin.

**Comment by tpersson** [comment]
Added to the documentation #857
