### ISSUE TITLE
Tack close orbit search does not work

### ISSUE THREAD

**Issue by ldeniau** [MethodicalAcceleratorDesign/MAD-X#799]
Looking at the code when comparing with MAD-NG, it seems that the closed orbit search in Track (6D) never really worked, which is not the same code as in Twiss (4D, works).
Two reasons:
1) the first iteration to build the Jacobian is made from 7 identical particles (no finite differences injected) and therefore the resulting Jacobian matrix is singular or close to, to machine precision (message reported by this module).
2) the finite difference dH is set to 1e-15, which is far too small for a Newton algorithm actually used. This makes the algorithm quickly unstable and loosing particles (e.g. secant almost // to axis makes next iteration far away from reference orbit).

**Comment by tpersson** [comment]
I have not checked the algorithm at all but I can say that it seems to find the correct closed orbit in at least my tests.

**Comment by tpersson** [comment]
The first run the particles are identical but then after the first run the 10e-15 is added and then it is run again. I have tried it for several orbits and the algorithm is able to find the closed orbit. I also think the 10e-15 is too small but it seems to work fine so I am a bit reluctant to change it..

**Comment by tpersson** [comment]
Fixed in #990
