### ISSUE TITLE
Documentation about "SELECT, flag=error, clear" seems incorrect

### ISSUE THREAD

**Issue by Dominik1123** [MethodicalAcceleratorDesign/MAD-X#803]
The documentation for `SELECT` states that:

> `CLEAR` deselects ALL positions in the sequence for the flag ”name”. This is the default for `ERROR` and `SEQEDIT` flags. e.g. `SELECT, FLAG=error;` is equivalent to `SELECT, FLAG=error, CLEAR;`

I tried by comparing results for `SELECT, FLAG=error;` and `SELECT, FLAG=error, CLEAR;` but they seem to differ. Actually when doing `SELECT, FLAG=error;` what seems to happen is:

    SELECT, FLAG=error, CLEAR;
    SELECT, FLAG=error, FULL;

This is different from what the documentation about `CLEAR` and `FULL` indicates.

Also the part about `CLEAR` being the default for `FLAG = error` seems confusing because for `SELECT, FLAG = error, RANGE = ...;` previous selections are not cleared.

### Complete example

    beam, beta = 0.6, gamma = 1.25, particle = "proton";

    base: quadrupole, l = 1;

    seq: sequence, l = 4, refer = entry;
        q0: base, k1 = 0.0, at = 0;
        q1: base, k1 = 0.1, at = 1;
        q2: base, k1 = 0.2, at = 2;
        q3: base, k1 = 0.3, at = 3;
    endsequence;

    use, sequence = seq;

    eoption, add;

    select, flag = error, clear;
    select, flag = error, range = q1;
    select, flag = error, range = q2;
    ealign, dx = 0.1;

    /* Using "SELECT, flag = error, clear;" works as expected:
       q[12] retain their dx error and q3->dy is set to 0.2.
       The MADX output reads:
           Assigned alignment errors to 1 elements
    */
    // select, flag = error, clear;

    /* Using "SELECT, flag = error;" the expectation is to get the same result as with "CLEAR"
    (according to the User's Guide):

       However MADX outputs the following:
           Assigned alignment errors to 3 elements
           Replaced alignment errors for 2 elements

       Checking the ESAVE file the following happened:
       dx is zero for all elements and dy is set to 0.2 for all element (including q0 and even "seq$start").
    This result is different from the "SELECT, flag = error, clear;" result.

       The result seems be similar as if we did:
           select, flag = error, clear;
           select, flag = error, full;

       But not:
           select, flag = error, clear, full;

       in which case MADX seems to do:
           select, flag = error, full;
           select, flag = error, clear;
    */
    // select, flag = error;

    select, flag = error, range = q3;
    ealign, dy = 0.2;

    select, flag = error, full;
    esave, file = "test_select.errors";

**Comment by tpersson** [comment]
I missed this issue previously but I will have a look at this today.

**Comment by tpersson** [comment]
You are right the documentation is very misleading. I will update it. Thanks for reporting and making such a clear example!

**Comment by tpersson** [comment]
This was fixed in the commit b9caa02cadb08f90729f7306901aea5c520ac481
