### ISSUE TITLE
Suggestion: Response Matrix

### ISSUE THREAD

**Issue by JoschD** [MethodicalAcceleratorDesign/MAD-X#831]
For many applications, e.g. calculation of corrections in the LHC, a quick access to a response matrix would be of great value. 

The command could be similar to:
```
SELECT, FLAG=twissresponse, PATTERN=BPM;
TWISSRESPONSE, SEQUENCE='lhcb1', PARAMETER=BETX, NAMES=kq5.l5b1, kq6.l5b1, DELTA=0.0002, FILE='filename.tfs'; 
```
changing each variable in NAMES independently by DELTA and calculating the difference of the given PARAMETER (after-before)/DELTA at the selected points, here creating a table of BPMs x NAMES.

**Comment by tpersson** [comment]
I think that would be a nice addition to MAD-X! We will try to find some time to implement it but might take a little while

**Comment by chernals** [comment]
That sounds like a job for the new MAD giving an open-box experience to the user :)

**Comment by ldeniau** [comment]
This can be done with macros and Rmatrix and/or Sector map, and maybe some post-processing. Including this feature in MAD-X is heavy work and should be performed with codes supporting generic knobs (e.g. MAD-NG).
