### ISSUE TITLE
Suggestion: Variable Influence

### ISSUE THREAD

**Issue by JoschD** [MethodicalAcceleratorDesign/MAD-X#832]
It would be very handy to have a direct overview, which variables are used to steer a specific magnet and vice versa: which magnets are influenced by which variable. 
Given a variable one could get a table of Elements x K-Values with the multiplier, e.g.

```
SELECT, FLAG=influence, PATTERN=M, COLUMNS=K1, K1L;
INFLUENCE, SEQUENCE=lhcb1, NAME=kq9.r1b1, FILE=file.tfs;
```

which would then output

|            NAME    |   K1  | K1L |
|----------------------|--------|-------|
| MQMC.9R1.B1  |   1   | 2.4  |
| MQM.9R1.B1     |   1   | 3.4  |

or similar.

**Comment by tpersson** [comment]
Just so I fully understand. You are interested in the values so not the variables that are used to set it up.  
The reason for this feature would be to have something faster than the TWISS if I understand correctly?

**Comment by JoschD** [comment]
Now that you mention it, I can imagine it is easier to make it the other way around: Given a Magnet name it gives you a table of circuit names and their coefficients.
E.g. for MQMC.9R1.B1

|            NAME    |   K1  |
|----------------------|--------|
| kq9.r1b1  |   1   |

I would need it in the originally stated direction, but I guess this way would already help as one should be able to easily invert the direction in an external program by reading the written files.

And yes, the way I am doing it right now is slow, but I am actually using the SURVEY command, similar as you would use TWISS in a response matrix: using it twice with the circuit under test once set to 0 and once to 1 and taking the difference between the outputs.

**Comment by JoschD** [comment]
Michael just hinted, that `FILL_KNOB` might be doing something similar (but kind of on a different axis). Maybe an extension of that would be a solution.

**Comment by ldeniau** [comment]
Creating a table or extending tables with element attributes can be done with macros (presented in MAD-X courses). Unless there is a strong requirement for something I missed, I suggest closing this issue.

**Comment by tpersson** [comment]
Maybe the example can be provide before closing the issue?

**Comment by ldeniau** [comment]
```
! Macros
tattrget(tblname, rowidx, attname): macro = {
  exec, tattrget__(tabstring(tblname, name, rowidx), attname);
};
tattrget__(elmname, attname): macro = {
  attname = elmname->attname;
};
tattrext(tblname, attname): macro = {
  write     , table=tblname, file="__tblname.tfs";
  delete    , table=tblname;
  readtable , table=tblname, file="__tblname.tfs";
  removefile, file="__tblname.tfs";
  tattrext.__i = 1; tattrext.__n = table(tblname, tablelength);
  while (tattrext.__i <= tattrext.__n) {
    setvars, table = tblname, row = tattrext.__i;
    exec, tattrget(tblname, $tattrext.__i, attname);
    fill, table = tblname, row = tattrext.__i;
    tattrext.__i = tattrext.__i + 1;
  }
};

! Example
seq : sequence, refer=entry, l=3;
df0: drift, at=0, l=1, slice = 0;
df1: drift, at=1, l=1, slice = 1;
df2: drift, at=2, l=1, slice = 2;
endsequence;
beam; use, sequence=seq;
select, flag=twiss, clear;
select, flag=twiss, column={name, s, l, betx, bety, slice};
twiss, betx=1, bety=1;
exec, tattrext(twiss, slice);
write, table=twiss, file="twiss_ext.tfs";

```
