### ISSUE TITLE
Suggestion: Full Regular Expression Support

### ISSUE THREAD

**Issue by JoschD** [MethodicalAcceleratorDesign/MAD-X#839]
Would it be possible to add more regular expression support to the `SELECT` command?
In particular, I am missing grouping `()` and the `?` operator, which would allow me to match all slices at the same time without the need to copy paste lines.

e.g. matching nonlinear correctors in IP1 and IP5
old:
```
select, flag = error, pattern = "MC[OST].*X\..*[15]";
select, flag = error, pattern = "MC[OST].*X\..*[15]\.\.\d+";
```

new:
```
select, flag = error, pattern = "MC[OST].*X\..*[15](\.\.\d+)?";
```

Edit: It's not a good example as the correctors are not sliced anyway :man_facepalming: .
Suggestion still stands, though.

**Comment by ldeniau** [comment]
Supporting "true" regular expressions, e.g. Perl REGEX, would break the backward compatibility of scripts and create some confusion. It is unlikely that MAD-X supports regular expressions one day.
