### ISSUE TITLE
Thick tracking in DIPOLE does not support TILT or K1S

### ISSUE THREAD

**Issue by chernals** [MethodicalAcceleratorDesign/MAD-X#841]
As far as I can tell, the thick tracking code (`tttdipole` in `trrun.f90`) does not take into account a  TILT or a K1S as it is done by `tttquad` (or should be done, see #840).

If it is indeed the case, this should be relatively easy to fix, based on the `tttquad` code.

**Comment by tpersson** [comment]
K1S is not an allowed attribute for the dipole. The tilt is done outside the element here as well. 

I don't see any issues here.

**Comment by chernals** [comment]
Alright then.

The implementation is a bit weird, as it is different for dipole than for quadrupole (I'm talking about the thick tracking routines).

Having a SBEND "degenerating" nicely to a quadrupole (with K1 and K1S) would be nice for matching/optimization algorithms.

**Comment by alatina** [comment]
In module TRACK the tilt is applied to *ALL* elements in the routine trrun, with the calls to tmali1 and tmali2. This includes of course also the element SBEND.

The SBEND does nicely transform into a pure quadrupole, if one has K0 = 0 and K1 != 0.

**Comment by alatina** [comment]
PS. K1S is not implemented into the SBEND. So, a SBEND can only transform into a normal quad, and not into a skew quad.

**Comment by chernals** [comment]
@alatina OK, this is what I meant, if we want to keep it that way it's fine.
