### ISSUE TITLE
Thick tracking in field-free dipole not consistent with tracking in drift

### ISSUE THREAD

**Issue by chernals** [MethodicalAcceleratorDesign/MAD-X#842]
When tracking through a dipole with zero field (ie. ANGLE=0 and K1=0, K1S=0, etc.) the results are not the same as for a tracking through a regular drift.

This is due to the fact that the pure DRIFT uses the solution the full Hamiltonian (total momentum, including the square root); `ttdrf` in `trrun.f90`.

But, the bends use the truncated Hamiltonian (both using `ttcfd` in `trrun.f90`).

A correct implementation should detect that a generic combined function dipole (`ttcfd`) degenerates to a drift and switch to `ttdrf`. This is already done in `ttquad` when this happens in a quadrupole.

**Comment by tpersson** [comment]
I added a check for the 0 strength dipole in a similar way as for the quadrupole. This is in PR #846

**Comment by chernals** [comment]
Awesome, thanks.
