### ISSUE TITLE
Tracking through dipole edges is incorrect

### ISSUE THREAD

**Issue by chernals** [MethodicalAcceleratorDesign/MAD-X#843]
Tracking through SBEND or RBEND, using `tttdipole` in `trrun.f90` uses `ttdpdg_map` to compute the transfer matrix of the field edge.

A correction is applied to the edge angle (E1 or E2) to take into account the physical extent of the field decay ("PSI" in Brown, SLAC75).

It seems that there is an error in `ttdpdg_map`, line 3233 :

`  corr = (h + h) * hgap * fint
`

Using `h+h` is probably done because Brown uses the total magnet gap, while the HGAP variable is the half-gap. However, this should then read

`  corr = h * (hgap + hgap) * fint
`

**Comment by chernals** [comment]
At this stage, either I'm completely loosing it or thick tracking in MAD-X is insane.

**Comment by tpersson** [comment]
@alatina if think you were the one that implemented this. Could you have a look?

**Comment by chernals** [comment]
For information, I performed a bunch of test with sequences defined either with SBENDs with E1 and E2 having non-zero values, or with DIPEDGE+SBEND+DIPEDGE, where the DIPEDGEs where tacking the values of E1 and E2.

With SBEND only there is no effect of E1/E2, while with DIPEDGE+SBEND+DIPEDGE I could recover the results of my own implementation. This coherent with the code analysis.

For information I have my own implementation of all this in Python along with an automated test suite (using CPYMAD to compare with MAD-X).

**Comment by chernals** [comment]
It seems that this is also confirmed in the MAD-8 physics guide, page 20-21.

**Comment by alatina** [comment]
The two lines of code
`corr = (h + h) * hgap * fint`
and 
`corr = h * (hgap + hgap) * fint`
are of course equivalent.
