### ISSUE TITLE
SBEND/RBEND tracking incorrectly uses E1, E2, H1 and H2

### ISSUE THREAD

**Issue by chernals** [MethodicalAcceleratorDesign/MAD-X#844]
Long story short, because this is a mess and I spent most of my Saturday evening on this...

Basically in `ttdipole` (`trrun.f90`) we call `ttdpdg_map` to apply the edge/fringe field effect, however there is a confusion between the parameters `h1` and `h2` (curvature of the magnetic boundary) with `h` (inverse of the bending radius).

To keep the tracking symplectic, the second order (tensor) terms involving `h1` and `h2` are not applied anyway, this is not the issue here, this is well-known. Basically that means that for a typical simulation, `h1` and `h2` are zero, which in turn makes the edge effects to completely vanish.

`if (node_value('kill_ent_fringe ') .eq. zero) &
       call ttdpdg_map(track, ktrack, e1, h1, hgap, fint, zero)`

should be

`if (node_value('kill_ent_fringe ') .eq. zero) &
       call ttdpdg_map(track, ktrack, e1, h, hgap, fint, zero)`

Same for the exit face.

**Comment by chernals** [comment]
For information, I performed a bunch of test with sequences defined either with SBENDs with E1 and E2 having non-zero values, or with DIPEDGE+SBEND+DIPEDGE, where the DIPEDGEs where tacking the values of E1 and E2.

With SBEND only there is no effect of E1/E2, while with DIPEDGE+SBEND+DIPEDGE I could recover the results of my own implementation. This coherent with the code analysis.

For information I have my own implementation of all this in Python along with an automated test suite (using CPYMAD to compare with MAD-X).

**Comment by alatina** [comment]
Hi Cedric, you are right. It must have been a typo.
Thanks for the bug report.

**Comment by tpersson** [comment]
Issue fixed in  #850
