### ISSUE TITLE
twiss fails for zero length solenoid

### ISSUE THREAD

**Issue by HelmutCERN** [MethodicalAcceleratorDesign/MAD-X#857]
! twiss fails with 5.05.02, final orbit    NaN
! seen for l=0 and beam with radiate
! worked with previous madx 5.04 versions

TestSeq: sequence, l = 1;
  mbas2.1r1: solenoid, l=0, at = 0.5;
endsequence;
beam,radiate;
use, sequence=TestSeq;
twiss,betx=1,bety=1,sequence=TestSeq,file="TestSeq_twiss.tfs";

**Comment by tpersson** [comment]
A check is added in TWISS and TRACK to avoid this and a warning is thrown if it happens and the radiation is ignored. #858
