### ISSUE TITLE
APERTURE is indefinitely busy when provided apertype is not on the reference orbit

### ISSUE THREAD

**Issue by roman-martin** [MethodicalAcceleratorDesign/MAD-X#866]
I am trying to find out if my kicked beam is going through the extraction channel of a septum, hence the off-reference-orbit aperture.

!----EXAMPLE-----------------------------------------------------------------------
mk1: hkicker, hkick:=kmk1;
!---marker with an aperture file with an aperture not on the reference orbit
TDI1: MARKER, apertype="offset_apertype.txt";
//TDI1: MARKER, apertype="offset_apertype_cheat.txt";

testseq: SEQUENCE, l = 20.0;
    mk1, at = 5;
    TDI1, at=20;
ENDSEQUENCE;

!---the usual stuff
BEAM, PARTICLE=PROTON, ENERGY=7000.0, EXN=2.2e-6, EYN=2.2e-6;
USE, SEQUENCE=testseq;

! turn on kicker
kmk1 = 0.02;

! twiss and aperture calculations
TWISS, BETX=1.0, bety=1.0, file=twiss.out;
APERTURE;
!---/EXAMPLE-----------------------------------------------------------------------

The content of offset_apertype.txt is
0.2    0.1
0.4     0.1
0.4     -0.1
0.2    -0.1

With this setting, the aperture command will just be busy indefinitely, never coming to any result but also never stopping. It is however possible to avoid this problem by introducing a little channel to the reference orbit, e.g in the offset_apertype_cheat.txt with the content
0.2     0.1
0.4     0.1
0.4    -0.1
0.2    -0.1
-0.01        -0.1
-0.01         0.1
0.01          0.1
0.01         -0.99
0.2           -0.99

It is interesting to note that the problem does not occur if the aperture is not too far off-reference-orbit, e.g.
0.1    0.1
0.4     0.1
0.4     -0.1
0.1    -0.1

**Comment by tpersson** [comment]
Thanks for the report. 
I can reproduce your error and I have found where in the code it gets stuck. However, I am still not sure why it get's stuck. I will investigate further during the day and get back with more information.

**Comment by roman-martin** [comment]
I just removed my workaround and this issue is still present in MAD-X 5.08.01

**Comment by tpersson** [comment]
Thanks for letting us know. I will have a look.
