### ISSUE TITLE
TILT in survey table filled with zeros

### ISSUE THREAD

**Issue by rdemaria** [MethodicalAcceleratorDesign/MAD-X#869]
using

select, flag=survey,               column=name,s,l,angle,x,y,z,theta,phi,psi,tilt,mech_sep,assembly_id,slot_id;

and then calling survey

returns a survey table where tilt values are always zero

**Comment by tpersson** [comment]
I just checked and there is actually not a tilt column in survey. It is not hard to add it in case you think it would be useful.

**Comment by rdemaria** [comment]
A tilt column has been requested by survey although a bit redundant.

**Comment by tpersson** [comment]
@rdemaria We are talking about the tilt as defined for the element? I just want to be sure before I update the tests.

**Comment by rdemaria** [comment]
yes. see email of  Mark Jones on 05 February 2020 16:07

**Comment by tpersson** [comment]
Thanks this is now fixed in PR #876

**Comment by tpersson** [comment]
Thanks this is fixed in #878
