### ISSUE TITLE
Modeling of the cavity RF (de)focusing 

### ISSUE THREAD

**Issue by JB-HSL** [MethodicalAcceleratorDesign/MAD-X#877]
As already discussed with Laurent. Would be nice to include the RF defocusing effect in RF cavities. Especially for the low energy simulations.
Attached, the matrix description.
Thanks, JB
[Cavity.pdf](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/4235508/Cavity.pdf)

**Comment by ldeniau** [comment]
Andrea already started to derive the RF (de)focusing effect from fringe fields (I attach his PDF).
[RF_focusing.pdf](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/4235576/RF_focusing.pdf)

**Comment by JB-HSL** [comment]
Be carrefull: The file I attached assumes "Linac" phase convention....

**Comment by tpersson** [comment]
This has been implemented in PR #894 . I won't close this yet because there are some things which are still unclear to me, such as the influence of pt on the beta function.

**Comment by tpersson** [comment]
After the tests of Piotr I consider this issue now closed. The impact of pt on beta-functions is understod and the results have been presented. A way to get the equivalent on-momentum beta-functions will be included in a future release.
