### ISSUE TITLE
`FINT` missing in `MAKETHIN` for `SBEND`

### ISSUE THREAD

**Issue by aoeftiger** [MethodicalAcceleratorDesign/MAD-X#881]
When calling `MAKETHIN` with dipedges on, the field integral attribute in the dipole fringe fields `FINT` gets lost in the resulting trailing `DIPEDGE`. It is set to zero, while in the leading `DIPEDGE` instance `FINT` is equal to the original `SBEND`'s one.

This bug occurs when creating a child of an `SBEND`. Tested with the current master branch at commit `b77389b`.

MWE:
```
a: sbend, l = 0.1, angle = 0.01, e1 = 0.005, hgap = 0.034, fint = 0.35;

b: a;

fodo: sequence, l = 10;
b, at = 5;
endsequence;

beam;
use, sequence=fodo;

select, flag=makethin, class=sbend, slice=9;
makethin, makedipedge=True, style=teapot, sequence=fodo;
```

This dipole `b` will be sliced into an entry dipedge, 9 slices `b..1` to `b..9` and an exit dipedge.
The entry dipedge has an `FINT=0.35` while the exit dipedge has an `FINT=0`!

This does not happen if I directly put `a` into the `fodo` sequence. However, a typical situation for a large realistic lattice such as for SIS100 [where dipole edges have quite an impact] demands defining a parent `SBEND` and then many children.
When slicing this thick lattice one runs into the above problem with all exit `DIPEDGE` instances erroneously having no field integral values.

I wouldn't know where to start searching for the reason of this bug in the source code..?

**Comment by aoeftiger** [comment]
Having `cpymad` installed, one can readily test this in python, see attached files..
[bugged_dex.zip](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/4356367/bugged_dex.zip)

**Comment by tpersson** [comment]
Thanks for the report and the clear example! I just had a look and I can confirm the problem. I will talk to Helmut who is the responsible for makethin.

**Comment by aoeftiger** [comment]
Thanks a lot, let me know if I can help more!

**Comment by tpersson** [comment]
The fix from Helmut is now be in the master. The example works when I tested it. Let us know if this solves your problem. Cheers!

**Comment by aoeftiger** [comment]
Excellent work, this solves the situation for me! Thanks a lot gents! :)
