### ISSUE TITLE
Twiss and summary tables

### ISSUE THREAD

**Issue by sterbini** [MethodicalAcceleratorDesign/MAD-X#883]
Hi,

the TWISS command allows to redefine the name of the TWISS table with the 'TABLE' parameter.
Is it possible to have a similar feature for the summary table? This would allow not to overwrite the summary tables of consecutive TWISS.

Cheers,
G.

**Comment by ldeniau** [comment]
Hi Guido,

I think that it is not possible to rename the table from the Twiss command because SUMM table is used internally in many places (hardcoded). I guess that it would need significant work to allow renaming the table. On the other hand, it is easy to clone a table with a couple of simple macro after you Twiss (adapted from my course, untested):

```
copytable(source, target) : macro = {
  copytable.__i = 1 ;
  copytable.__n = table(source, tablelength) ;
  while ( copytable.__i <= copytable.__n ) {
    setvars, table = source, row = copytable.__i ;
    fill, table = target, row = copytable.__i ;
    copytable.__i = copytable.__i + 1 ;
  }
}

clonesumm(target) : macro = {
  create, table = target, column = {
    "length", "orbit5", "alfa", "gammatr", "q1",
    "dq1", "betxmax", "dxmax", "dxrms", "xcomax",
    "xcorms", "q2", "dq2", "betymax", "dymax",
    "dyrms", "ycomax", "ycorms", "deltap",
    "synch_1","synch_2","synch_3","synch_4","synch_5",
    "nflips"
  } ;
  exec, copytable(summ, target) ;
}
```

**Comment by sterbini** [comment]
Hi Laurent, 
Thank you very much for the explanation and the suggestions.
I will try it out.
Cheers,
G.

**Comment by ldeniau** [comment]
Any news? Is the proposed solution worked for you?

**Comment by sterbini** [comment]
Yes! Sorry for not reporting. I am copying it with the macros you suggested.
Thanks!
