### ISSUE TITLE
RF-cavity adding the pt at wrong place

### ISSUE THREAD

**Issue by tpersson** [MethodicalAcceleratorDesign/MAD-X#886]
The RF-cavity in TWISS can handle a thick cavity by adding a drift on each side. However, the change in pt when tracking is on (ptrk) is done before the first drift. This means that this drift will already be off-momentum if the beam is accelerated. It is a small effect but will change it at the same time as for the rffringe fields.

**Comment by ldeniau** [comment]
Good point...

**Comment by tpersson** [comment]
This is fixed in PR #894
