### ISSUE TITLE
Weak focusing for thin dipoles in TWISS

### ISSUE THREAD

**Issue by tpersson** [MethodicalAcceleratorDesign/MAD-X#888]
I saw an issue where the chromaticity using the CHROM option and the "normal" was not giving the same result for a case with 0 coupling. It seems to me to come from the weak focusing for a thin dipole 
It seems that there is a division with the (1+dp)^2 for the thin focusing when I think it should only be scaled with  (1+dp). The line looks like:
     re(2,1) = re(2,1) - dipr*dipr/elrad, where dipr = k0L/(1+dp). => re21 = (k0/(1+deltap))^2/lrad

If I add multiply the line above with (1+dp) (it is easier to do it in this way because of all the rotations that takes place before.. ) then re21 = (k0^2/(1+deltap))/lrad 

After this modifications the results then becomes consistent with both MAD-X without (chrom option) SixTrack and PTC. 

You can see the changes in the code in PR #887 (this also fixes so that chromaticity is given as DQ/DPT even when the chrom option is in use. 
The link to an example is attached below.

Anyone has any thoughts? @rdemaria @alatina @ldeniau

**Comment by tpersson** [comment]
[togihub.madx.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/4480981/togihub.madx.txt)

**Comment by tpersson** [comment]
After a short discussion with Riccardo which pointed me in the right direction I also found this :
https://www.cockcroft.ac.uk/wp-content/uploads/2014/12/wolski-3.pdf

It is very clear that there is a geometrical term and a kind of bending term and my proposed change is therefore correct.

**Comment by rdemaria** [comment]
I think dipr*dipr should be replaced by dipr*h

**Comment by tpersson** [comment]
Absolutely! I was just changing that now

**Comment by tpersson** [comment]
Thanks for the comment... Just realized that the "angle" is only for horizontal dipoles, not impossible to change but a bit tricky.. I think we can leave it like this for now..

**Comment by rdemaria** [comment]
Can't you use `angle` and `tilt`? I am not familiar with the code, but I expect you have something similar for other energy dependent effects

**Comment by tpersson** [comment]
If you make the vertical dipole from the horizontal using tilt you will get the same result indeed but if you instead would have ksl and an angle then the angle would still be in the horizontal plane. I wasn't the one who implemented this and don't know how well this is documented.. I will have a look. 
I agree that you can make a vertical dipole just have to be careful how it is done.

**Comment by tpersson** [comment]
This is fixed in PR #887
