### ISSUE TITLE
Strange behaviour of efcomp

### ISSUE THREAD

**Issue by alatina** [MethodicalAcceleratorDesign/MAD-X#906]
From Rogelio:

«I just came across a strange behavior of EFCOMP when order is not given.
In the manual it is written that the default value of order is 0.
I was trusting on this but I was getting wrong results if order is not specified.
I made a minimal standalone example that saves the errors and the twiss when
order is given as 0 and when it is not given. Results are different, see below.»

[test_efcomp.madx.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/4778771/test_efcomp.madx.txt)

**Comment by tpersson** [comment]
Closing this since this was fixed in #907
