### ISSUE TITLE
interpolate plots with quad offsets create fake dispersion peaks

### ISSUE THREAD

**Issue by orblancog** [MethodicalAcceleratorDesign/MAD-X#908]
Dear madx team,

I'm working on a cell where quads are displaced a few cm and I need to check the dispersion created by the feed-down dipole component.

I see very strange peaks due to the interpolate function that make the plots discontinuous.

As a workaround one coud remove the interpolation and slice the magnets which is ok for small lattices, but, 

Is there any solution to this situation ?

I attach a small madx script and the post-script output with mad-x 5.05.02 in linux.
[quadoffsets.zip](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/4791402/quadoffsets.zip)

o

-- 
Oscar BLANCO

**Comment by ldeniau** [comment]
Thank you Oscar, I confirm the problem.

**Comment by tpersson** [comment]
The problem is there but since it is possible to overcome, as you said with thick slicing, it will not be fixed at this moment.  Just for reference I attach an example with the thick slicing.

**Comment by tpersson** [comment]
[quadoffsets_withThickSlice.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/4930183/quadoffsets_withThickSlice.txt)
