### ISSUE TITLE
ptc_eplacement warning when gcs is set explicitly

### ISSUE THREAD

**Issue by orblancog** [MethodicalAcceleratorDesign/MAD-X#909]
Dear madx team,

when creating quad offsets within ptc, the ptc_eplacement command launches a warning when refframe=gcs is set explicitly. 

I attach a small script calling ptc_eplacement as:
`ptc_eplacement, range="vq01", refframe=gcs, x= 0.01;`

Executed as :
`
$ madx movequadWptcgcs.madx | grep -i warning
`
`
++++++ warning: mad_ptc.c: pro_ptc_eplacement: did not recognize string describing refframe, using default   gcs
`

I'm using mad-x 5.05.02 on linux 64 bits.

o
--
Oscar BLANCO

[ptceplacementwarn.zip](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/4797808/ptceplacementwarn.zip)

**Comment by tpersson** [comment]
This is fixed in PR #912
