### ISSUE TITLE
GNU Fortran GCC 10 cmake and fortran compile errors

### ISSUE THREAD

**Issue by HelmutCERN** [MethodicalAcceleratorDesign/MAD-X#918]
After switching recently from GNU GCC 9 to 10,  exact version as visible with gfortran --version:
GNU Fortran (Homebrew GCC 10.1.0) 10.1.0

cmake fails : 
-- Checking whether /usr/local/bin/gfortran supports Fortran 90 - yes
-- Mad-X version: 5.05.02
-- Version num: 50502
-- Version date: 2019.07.25
CMake Error at cmake/compilers/setupGNU.cmake:13 (if):
  if given arguments:

    "VERSION_GREATER" "4.3.9"

  Unknown arguments specified
Call Stack (most recent call first):
  cmake/setupCompilerSpecifics.cmake:12 (include)
  CMakeLists.txt:29 (include)

Seems CMAKE_Fortran_COMPILER_VERSION is now empty.
When I set manually
set(CMAKE_Fortran_COMPILER_VERSION "10.1.0")
in setupGNU.cmake  cmake works.

Compiling fails with many BOZ literal fortran errors in util.f90.
The first two errors are shown here: 
  199 |   integer(Single), parameter :: sNaN    = Z"7FC00000"
      |                                         1
Error: BOZ literal constant at (1) is neither a data-stmt-constant nor an actual argument to INT, REAL, DBLE, or CMPLX intrinsic function [see '-fno-allow-invalid-boz']
/Users/hbu/madX/src/util.f90:200:41:

  200 |   integer(Single), parameter :: sPosInf = Z"7F800000"
      |                                         1
Error: BOZ literal constant at (1) is neither a data-stmt-constant nor an actual argument to INT, REAL, DBLE, or CMPLX intrinsic function [see '-fno-allow-invalid-boz']
/Users/hbu/madX/src/util.f90:201:41:

To be able to continue MAD-X development I currently work with the fortran compiler option
-fallow-invalid-boz
to hide these errors and get object files

**Comment by ldeniau** [comment]
Those points have been fixed in the built system of MAD-X. Need volunteers to update the CMake system.

**Comment by ldeniau** [comment]
Both CMake and Make systems have been updated.
