### ISSUE TITLE
Documentation of the track option 'KEEPTRACK' needs update

### ISSUE THREAD

**Issue by chernals** [MethodicalAcceleratorDesign/MAD-X#932]
The manual lists the option `KEEPTRACK` under the `run` command of track:

`KEEPTRACK: a logical flag to keep data from previous tracking and append new results to tables. (Default: false)`

However, this gives the following error: `+=+=+= fatal: illegal keyword: keeptrack`.

Looking at the code, it seems that `KEEPTRACK` is an option of the `TRACK` command (`mad_dict.c`):

"track: track track 1 0 "
```
"deltap   = [r, 0], "
"onepass  = [l, false, true], "
"update   = [l, false, true], "
"damp     = [l, false, true], "
"quantum  = [l, false, true], "
"seed     = [i, 123456789], "
"dump     = [l, false, true], "
/* "fast     = [l, false, true], " */
"aperture = [l, false, true], "
"onetable = [l, false, true], "
"recloss  = [l, false, true], "
"keeptrack= [l, false, true], "
"file     = [s, track, track], "
"only_average = [l, false, true], "
"extension= [s, none, none]; "
" "
```

(by the way, it also seems that `only_average` and `extension` are not documented).

**Comment by chernals** [comment]
Related commits: `f5a1b2e6c79949ea50fce16f2aca7d2ac4ca06e2` (use of the option) `f60b73c08a9977375f5633fd30edd7ca34517af4` (update of the dictionnary).

**Comment by chernals** [comment]
PR #933 is merged.

**Comment by tpersson** [comment]
I think we can close this one after the PR, right?

**Comment by chernals** [comment]
Yes !
