### ISSUE TITLE
Track option UPDATE requires definition of tr$macro

### ISSUE THREAD

**Issue by Oskari-Tuormaa** [MethodicalAcceleratorDesign/MAD-X#935]
Setting the tracking module option `UPDATE` to true, without defining the macro `tr$macro` gives the following error: `+=+=+= fatal: illegal keyword: tr$macro`.

Defining the macro, even while empty, fixes the problem:

```
tr$macro(turn) : macro={};
```

It is however not described in the MAD-X User's Guide that the macro must be defined by the user.

**Comment by chernals** [comment]
It would be interesting to investigate if it is possible to predefine the macro or have a kind of "empty lambda" already defined.

**Comment by tpersson** [comment]
I agree that the error message is not ideal but what is the use of UPDATE without the macro?

**Comment by tpersson** [comment]
I have added this to the documentation in PR #967

**Comment by tpersson** [comment]
Documentation is now updated in #967
