### ISSUE TITLE
Discrepancy in table TRACKSUMM of PTC tracking

### ISSUE THREAD

**Issue by bogomyag** [MethodicalAcceleratorDesign/MAD-X#962]
I track for 16 turns 15 particles with different X and PT, then in TRACKSUMM table I see that initial coordinates are correct but the final ones are mismatched, i.e. particle 9 having initial PT=-0.5, has PT=0.5 in the second half of the TRACKSUMM table, and particle 10 has correct values of PT.
Also X,PX of the particles 9 and 10 are different between TRACKSUMM and TRACKONE.
[Test-1.zip](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/5437560/Test-1.zip)

**Comment by bogomyag** [comment]
I forgot to mention the version of madx
  ++++++++++++++++++++++++++++++++++++++++++++
  +     MAD-X 5.06.00  (64 bit, Windows)     +
  + Support: mad@cern.ch, http://cern.ch/mad +
  + Release   date: 2020.08.13               +
  + Execution date: 2020.10.27 09:05:47      +
  ++++++++++++++++++++++++++++++++++++++++++++

**Comment by tpersson** [comment]
Thanks for the report. I will have a look.

**Comment by tpersson** [comment]
It is indeed very strange this behaviour and I have been looking to fully understand it this enitre morning. I have found that it is actually linked to particle 8 beeing lost which for some reason confuses it so if I make sure it doesn't get lost everything looks fine for me. I will continue a bit more and ask the other collegues in the team if they have any ideas...

**Comment by tpersson** [comment]
This bug was fixed in collaboration with @piotrskowronski . It was a problem with the indexing when a particle was lost. This meant that any particle that was lost after the inital lost particle gets the wrong coordinates.

**Comment by bogomyag** [comment]
Thank you. When is it going to be included in the release?
