### ISSUE TITLE
crab cavity voltages added to RF cavity voltages in fc.3.aux by sixtrack conversion

### ISSUE THREAD

**Issue by rdemaria** [MethodicalAcceleratorDesign/MAD-X#964]
When crab cavities are present, we see large voltages coming from the sum of both types

SYNC
       35640  0.000349    **42.599** 0.  26658.883200  938.272088  1
      1.        1.
NEXT

**Comment by tpersson** [comment]
I will have a look straight away. Do you know if it is only when they are defined as crab or also as RF-multi?

**Comment by tpersson** [comment]
It does look like it is only for the crab cavity.

**Comment by rdemaria** [comment]
no, I have not checked. Frederik found that in fc.3.aux there is sum(Vrf)+2*sum(Vcrab)...
