### ISSUE TITLE
User Guide section about MAKETHIN should mention that afterwards the thin sequence must be loaded via USE

### ISSUE THREAD

**Issue by Dominik1123** [MethodicalAcceleratorDesign/MAD-X#985]
In the User Guide there is no mention of the fact that after `MAKETHIN, sequence = xxx` one must do `USE, sequence = xxx` in order to activate/load the thin sequence. Especially the subsection [23.4 Additional information](http://mad.web.cern.ch/mad/webguide/manual.html#Ch23.S4) mentions that:

> The new sequence has the same name as the original. The original sequence is replaced by the new one in memory. If the original sequence is needed for further processing in `MAD-X`, it should be reloaded.

This strongly suggests that loading is done automatically and no further `USE` is required. Omitting the `USE` can however lead to surprising results.

**Comment by tpersson** [comment]
I will add this to the documentation to be clear that this is needed.

**Comment by tpersson** [comment]
Documented in 1008
