### ISSUE TITLE
Build manylinux as github action doesn't work 

### ISSUE THREAD

**Issue by tpersson** [MethodicalAcceleratorDesign/MAD-X#987]
Most of the builds on the GitHub actions are building nicley but the manylinux fails before even the tests have been run. @coldfix  maybe you know straight away or after a quick check why it doesn't work, if not I will investigate. Many thanks in advance.

**Comment by tpersson** [comment]
Note that for all the other where we also build on linux platforms it works fine so I think it simply some error in the script.

**Comment by coldfix** [comment]
Which failing tests are you referring to? All recent runs under actions seem to have succeeded?

**Comment by ldeniau** [comment]
Looking at the details of some tests shows that they failed to build and run MAD-X while reporting success...

**Comment by tpersson** [comment]
An example is:
test (ubuntu-16.04, cmake, 1_x86_64) under manylinux

**Comment by coldfix** [comment]
Thanks, I'll check in the next days.
