### ISSUE TITLE
User Manual issues

### ISSUE THREAD

**Issue by kyrsjo** [MethodicalAcceleratorDesign/MAD-X#996]
A few issues/errors in the user manual:

- In Section 1.7.3 it says "And since PT=BETA*DELTAP,", while in 1.7.4 it says "Since PT=BETA/DELTAP,". Only one of these can be correct.
- On page 108 (example for SEQUENCE), the magnet "qf" is defined as defocusing, and "qd" is focusing. While not strictly wrong, it has the potential to confuse new users.

**Comment by rdemaria** [comment]
Well they are both wrong ;-)

d delta/ d pt = 1/ beta
1+delta = sqrt(pt^2 + 2 pt/beta0   + 1 )

**Comment by ldeniau** [comment]
I agree, this is probably dating from translation from html pages, when we were still trying to figure out which cannonical variables are used in MAD-X...

**Comment by tpersson** [comment]
Indeed they are not fully correct any of them. I have already had a discussion with @kyrsjo but I will update the manual and in some way also include a short derivation to show the correct formula and also why the pt=beta*dp is good in enough in most cases.

**Comment by tpersson** [comment]
Corrected this and add a short derivation in the end #1008
